lmfit/lmfit-py

lmfit/_differentialevolution.py
lmfit/minimizer.py

Tested in a virtualenv with scipy0.13.3 and lmfit-py/master

BUG: _differential_evolution, couldn't be imported with scipy0.13. closes #177

---

lmfit/model.py
tests/test_model.py

* Add tests for hints propagation from base models to composite models
* Improve error messages for name collisions and non initialized parameters

Add CompositeModel hints test

---

doc/_templates/indexsidebar.html
doc/contents.rst
doc/faq.rst
doc/index.rst
doc/support.rst

doc changes only: start of in-document FAQ, and more prominent link to mailing list.

doc: add start of FAQ, and better links to support

---

lmfit/models.py

Guard against missing docstrings under python -OO (Fixes #191)

---

lmfit/parameter.py

This addresses issue #198 
I cannot think of any reason where the current behavior is desirable.

Parameters.__add__() makes a fresh copy for return

---

doc/faq.rst
doc/intro.rst
doc/model.rst

Great tutorial, I was looking exactly for these features! 
This is just a bunch of typo fixes and rephrase suggestions
I hope my suggestions are helpful.

DOC: typo fixes and rephrase suggestions

---

lmfit/parameter.py

bugfix: allow Parameter.max = 0

---

lmfit/__init__.py

this addresses #215, and may give a slight improvement in import time.

remove import of ui from __init__.py

---

Contributing.md
README.rst
doc/_templates/indexsidebar.html
doc/faq.rst

1. add direct link to mailing list on sidebar of main web page
2. add Contributing.md to give some guidance on contributions, issues, etc.

Issues doc

---

lmfit/ui/ipy_fitter.py

fix  #246 (for my use case at least)

IPython 4.0 compatibility fix for Widgets

---

lmfit/ui/__init__.py
lmfit/ui/ipy_fitter.py

This is a belated fix for the NotebookFitter on IPython 4.0. I believe it should also work correctly on IPython 2.x and 3.x, but I am struggling to test it just this moment -- some unrelated lapack error is blocking my progress.

Fix ipyfitter

---

MANIFEST.in
lmfit/minimizer.py

make sure update_constraints() is called in residual function before calling users objective function.

make sure update_constraints() is called

---

tests/test_model.py

asteval and add_param_hint() error

Add test for bug #271

---

lmfit/model.py

Model conf interval (round2)

---

.travis.yml
examples/doc_model2.py
lmfit/asteval.py
lmfit/model.py
tests/test_algebraic_constraint.py

This addresses #281, fixing use of function calls in constraint expressions for Py3.5
Also includes a couple small code cleanups.

Py35 updates

---

lmfit/parameter.py

Some speed improvements in `Parameters.update_constraints`

ENH: speeding up update_constraints

---

lmfit/minimizer.py
lmfit/parameter.py

various PEP8 changes. (Pycharm suggests that they're PEP8 problems). @newville, if this isn't important then feel free to close PR.

PEP8: various PEP8 and style fixes

---

doc/fitting.rst
lmfit/minimizer.py
tests/test_nose.py

Added `seed` kwd to `Minimizer.emcee` for reproducible sampling.
Added tests and documentation for new kwd.

ENH: reproducible sampling with emcee - added seed

---

examples/complex_resonator_model.ipynb
lmfit/model.py
lmfit/models.py
tests/test_model.py

This pull request allows models to return complex values. A simple, but reasonably sensible residual function is provided.
Currently all tests pass _except_ the test_data_alignment test which is relevant for pandas Series data. I'm not yet sure how to address this, but I will attempt to figure out a solution.
The present implementation is slightly cryptic to gain efficiency because it occurs at one of the most performance critical portions of the code: the evaluation of the residual function.

Rudimentary support for complex models

---

lmfit/model.py

Add method to pretty-print Model.param_hints

---

lmfit/parameter.py

Remove long() and use builtins.int() for py2/3 comp

---

lmfit/model.py

This PR addresses Issue #339, I added in optional xlabel and ylabel arguments for labeling plots.

Added optional parameters xlabel and ylabel for plots

---

doc/model.rst
lmfit/model.py
tests/test_model.py

This allows evaluating a Model and ModelResult at a scalar value, addressing #333

Model eval scalar

---

lmfit/minimizer.py

Fix the factor -2*log-likelihood used to compute AIC and BIC statistics.

Fix log-likelihood computation

---

examples/complex_resonator_model.ipynb
examples/lmfit-model.ipynb

Fix errors (missing imports, py3 prints, etc.) and add title and one-line description to notebooks.
In this PR notebooks are unexecuted (no output).
Fix #347.

Docs: fix errors in example notebooks

---

lmfit/minimizer.py

Minor docs fix. Addresses #359 for 0.9.5.

Docs: remove no longer true note

---

doc/conf.py
doc/fitting.rst
lmfit/minimizer.py

I enabled autodoc for the Minimizer class.
I basically removed the manual documentation copying in the docstring the things that were missing.
I also fixed some formattings, and math expression (\n, \r, \f need to be escaped in latex equations).
Builds correctly locally.

Autodoc Minimizer class

---

lmfit/minimizer.py

Minor changes to emcee documentation based on a question to the ML.

DOC: improve emcee doc

---

doc/intro.rst
lmfit/models.py

a few more doc tweaks for 0.9.6

---

lmfit/parameter.py
tests/test_parameters.py

Fix copy param

---

lmfit/models.py

Add height parameter to pseudovoigtmodel based on equations in docs.

height param pseudovoigtmodel

---

lmfit/asteval.py
lmfit/models.py

The current estimation of Voigt height can be off by a significant amount. This will calculate the true value. Docs already state height is included.

True calc of Voigt height

---

lmfit/models.py

Add missing pi to pseudovoigt height

---

doc/model.rst

Correct some examples in `model.rst`
This PR addresses Issue #432

Minor correction to the docs

---

examples/lmfit_emcee_model_selection.ipynb

This should fix the emcee example referred to in #442.

Fixed emcee model selection example

---

examples/doc_model_loadmodel.py
examples/doc_model_loadmodelresult.py
examples/doc_model_loadmodelresult2.py
examples/doc_model_savemodel.py
examples/doc_model_savemodelresult.py
examples/doc_model_savemodelresult2.py
lmfit/model.py
lmfit/models.py

The merge of #448 reverted some earlier style-related changes to the example files, these are reintroduced here. 
In addition, two small suggested changes to the code introduced in #448 by @openafox (which is great by the way, thanks!). There is one unused, left-over ```fwhm_factor```, and I would suggest to use the full ```fwhm_factor``` expression for Gaussian models. 
Finally, one change as prompted discussed on the [mailinglist](https://groups.google.com/forum/#!topic/lmfit-py/rekwbFVJy2c) to plot the fit on top of the data points by default in the ```ModelResult.plot_fit()``` function.

Small fixes after merge

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

This PR includes the following changes in files related to GitHub:
- use markdown and update text in ```contributing.md```
- use markdown and update the ```issues_template.md```: some textual changes and indicate more clearly what information is needed when submitting an Issue. 
- fix typo in ```pull_request_template.md```

Updates to contributing and Issue/PR templates

---

lmfit/models.py

This addresses #489, using the remedy proposed there....

specify max_time and evaluation time for ExpressionModel

---

doc/builtin_models.rst
lmfit/models.py

Adds SkewedVoigtModel, as requested in #493

add skewed voigt model

---

lmfit/minimizer.py
tests/test_basinhopping.py

Allow for scipy dev version; fix #497

---

doc/faq.rst
lmfit/model.py

Added a new keyword argument to the `.plot`, `.plot_fit`, and `.plot_residual` methods of the `ModelResult` class in model.py. Keyword argument added at the end so as not to break any positional calls in older code.
The new keyword `parse_complex` can take one of four values: `abs`, `angle`, `real`, `imag` and describes how to convert a complex-valued array to a real valued array so it may be plotted. The various options implement the numpy functions of the same name. The default value is `abs` so that the magnitude is plotted. The `Model` class already properly calculates residuals for complex-valued model functions, so no changes were needed there. In fact, this new functionality was added to bring `ModelResult` up to speed with `Model` vis-a-vis complex numbers.
Additionally, it …

Handle plotting of complex-valued models in ModelResult class

---

doc/faq.rst
lmfit/model.py

Revert "Handle plotting of complex-valued models in ModelResult class"

---

lmfit/models.py
tests/test_covariance_matrix.py

This improves FWHM for VoigtModel as described in https://groups.google.com/d/msg/lmfit-py/lqXORBFD7dc/w09Y1UuqCwAJ  and references therein.    This PR also fixes one tested value in test_covariance_matrix.py to better reflect the newly computed value.

improved FWHM calculation for VoigtModel, especially for gamma!=sigma

---

doc/whatsnew.rst
lmfit/__init__.py
lmfit/_ampgo.py
lmfit/confidence.py
lmfit/jsonutils.py
lmfit/minimizer.py
lmfit/model.py
lmfit/models.py
lmfit/parameter.py
lmfit/printfuncs.py
tests/test_nose.py
tests/test_parameters.py

This PR contains some housekeeping on the codebase, mainly prompted by static code analysis. Most changes are minor, but please check at least the two below:
- remove the ```isclose``` function from ```parameter.py``` and use the (same) one from ```numpy```
- propagate the ```**kws``` argument to ```model.dumps()``` to ```json.dumps()```; at least from the docstring that seems to be the intention

Minor code maintenance

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
README.rst

This PR updates the GitHub templates for Contributing, Issues and PRs. Additionally, some additional badges, a few small textual changes/re-formatting of ```README.rst```.

GitHub template updates

---

.pre-commit-config.yaml
lmfit/ui/__init__.py
setup.cfg
tests/test_height_fwhm.py

- update the pre-commit hooks to their latest versions
- fix reported style/conding issues

Update pre-commit hooks

---

lmfit/parameter.py
tests/test_saveload.py

This will fix #553 by explicitly looking for tagged "unique symbols " and doing a full import (if necessary, and if possible).

Savemodel fixes

---

lmfit/printfuncs.py

clean up parameter html table

---

lmfit/minimizer.py
tests/test_least_squares.py

Fixes #588.
The documentation for [`scipy.optimize.least_squares`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.least_squares.html) indicates that the Jacobian can be either `numpy.ndarray`, a sparse matrix (instance of `scipy.sparse.spmatrix`), or a `scipy.sparse.linalg.LinearOperator`. However, the existing calculation of the Hessian works only for `numpy.ndarray` because `numpy.matmul` does not support the other possible types.
https://github.com/lmfit/lmfit-py/blob/d7b408baa64821f4356cff9c32a199bc53becd93/lmfit/minimizer.py#L1430
In this pull request, the type of the Jacobian is tested and the Hessian calculated accordingly.
Python: 3.7.3 (default, May 26 2019, 09:41:28)
lmfit: 0.9.14+2.g36a022f, scipy: 1.3.0, numpy: 1.16.3, …

Add support for non-array Jacobian types in least_squares

---

doc/confidence.rst

Could also be automatically done, but this is better than nothing.
Can't test locally right now, hence lets wait for ci.
- [x ] Documentation / examples

[Doc] Give missing stderr workaround for ci calculations

---

lmfit/confidence.py
tests/test_confidence.py

Fixes #597 and improves handling of bounds in conf_interval.
Have you
- [x ] referenced existing Issue and/or provided relevant link to mailing list?
- [ x] squashed/minimized your commits and written descriptive commit messages?

FIX: Fix #597 and improve bound handling in conf_interval

---

lmfit/parameter.py
tests/test_parameters.py

This addresses #607 
- [x ] Bug fix
Tests (including added test based on #607) works for me with
Python: 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0]
lmfit: 0.9.14+40.gd001938, scipy: 1.3.1, numpy: 1.17.2, asteval: 0.9.16, uncertainties: 3.0.2, six: 1.12.0
Have you

fix for adding parameters with user-defined symbols

---

lmfit/confidence.py
tests/test_confidence.py

Fixes the `prob_func` functionality. Since it did not work in master also refactored it for better generalizations. 
- [x ] Bug fix
- [x ] Refactoring / maintenance
Have you
- [ x] squashed/minimized your commits and written descriptive commit messages?
- [ x] added or updated existing tests to cover the changes?

Fix and refactor prob_func

---

.pre-commit-config.yaml
INSTALL
THANKS.txt
doc/doc_examples_to_gallery.py
doc/installation.rst
doc/whatsnew.rst
examples/example_brute.py
examples/example_confidence_interval.py
examples/example_detect_outliers.py
lmfit/lineshapes.py
lmfit/minimizer.py
lmfit/parameter.py
lmfit/printfuncs.py
setup.cfg
tests/test_lineshapes_models.py
tests/test_parameters.py
tests/test_saveload.py

Change `doc\installation.rst` to clearly state end of support for Python 2.7

announce end of support for Python 2.7

---

lmfit/model.py
tests/test_saveload.py

This addresses issue #621 in which ModelResult.dump() fails with non-default methods such as brute.
https://groups.google.com/forum/#!topic/lmfit-py/3iXyz7aCbDQ
Python: 3.8.1 (default, Jan  8 2020, 16:15:59) 
lmfit: 1.0.0+16.g1393ec9e, scipy: 1.4.1, numpy: 1.18.2, asteval: 0.9.18, uncertainties: 3.1.2
Have you
No new functions except in tests.
documentation unchanged.

fix dumps and add test

---

doc/builtin_models.rst
lmfit/lineshapes.py
lmfit/models.py
tests/test_lineshapes_models.py

This adds thermal distribution lineshapes and model following mailing list discussion here:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/lmfit-py/e5GPIAAz5HA/3sIrKOW-AgAJa
@newville 
lmfit: 1.0.0+16.g4485ecbc.dirty, scipy: 1.4.1, numpy: 1.18.2, asteval: 0.9.18, uncertainties: 3.1.2
Have you
The code passes flake8. pydocstyle thew many complaints about existing functions, so I was unsure what was needed here. 
There are two simple commits, which seems manageable without a squash.

Add thermal distribution model and lineshape

---

lmfit/models.py

This removes several inaccurate calculations of FWHM, addressing issue #616 and https://groups.google.com/forum/#!topic/lmfit-py/FPlIjICfHo0
Python: 3.7.6 (default, Jan  8 2020, 13:42:34) 
lmfit: 1.0.0+31.gd086e62, scipy: 1.3.1, numpy: 1.18.1, asteval: 0.9.18, uncertainties: 3.0.2
Have you

remove several inaccurate fwhm, label others as estimates

---

lmfit/model.py

This adds a check to ModelResult.eval_uncertainty, which will fail if the uncertainty of any of the parameters has a `None`.   Here we add a check for `is any par.stderr None` and return an array of 0s.
Python: 3.7.7 (default, Mar 23 2020, 17:31:31)
lmfit: 1.0.0+44.gb9c8759, scipy: 1.4.1, numpy: 1.18.1, asteval: 0.9.18, uncertainties: 3.1.2
Have you

add check if ModelResult.eval_uncertainty()

---

.pre-commit-config.yaml
INSTALL
THANKS.txt
doc/whatsnew.rst
lmfit/minimizer.py
lmfit/model.py
tests/test_itercb.py
tests/test_max_nfev.py

As discussed in another PR: this contains a few style and docstring changes to make things slightly more consistent and clear (in my opinion). 
Additionally, a few more tests and a `What's new` entry.
lmfit: 1.0.0+86.gb35b4a5, scipy: 1.4.1, numpy: 1.18.2, asteval: 0.9.18, uncertainties: 3.1.2
Have you

prepare for release

---

doc/builtin_models.rst
examples/example_two_dimensional_peak.py
lmfit/lineshapes.py
lmfit/models.py
tests/test_builtin_models.py

This adds examples for fitting two-dimensional peaks and a related function and model.  Sphinx v3.0.3 (the default selected by pip) was throwing an error saying that `` jupyter_sphinx.execute`` needs to be updated to ``jupyter_sphinx``, which I did.  
lmfit: 1.0.0+90.g0bce6be, scipy: 1.4.1, numpy: 1.18.4, asteval: 0.9.18, uncertainties: 3.1.2
Have you
https://groups.google.com/forum/#!topic/lmfit-py/-rP1sd47HkA
The added functions are executed by the pre-existing tests.

add two dimensional gaussian

---

lmfit/models.py

fix issue about lognormal center

---

doc/conf.py
doc/doc_examples_to_gallery.py
examples/doc_fitting_emcee.py
examples/example_brute.py
examples/example_fit_multi_datasets.py
examples/example_two_dimensional_peak.py
lmfit/jsonutils.py
lmfit/lineshapes.py
lmfit/minimizer.py
lmfit/models.py
lmfit/parameter.py
lmfit/printfuncs.py
tests/test_max_nfev.py
tests/test_model.py
tests/test_parameters.py
tests/test_printfuncs.py

This PR contains fixes to issues reported by pylint and [LGTM](https://lgtm.com/projects/g/lmfit/lmfit-py/), and some clean-up of unused code. Additionally, we no suppress warnings and output from `matplotlib` in the gallery.
Please take a look through the individual commits and let me know if there are any changes you do not agree with.
lmfit: 1.0.1+29.g36541e6, scipy: 1.4.1, numpy: 1.18.5, asteval: 0.9.18, uncertainties: 3.1.2
Have you

Fix issues reported by static code analysis

---

.codecov.yml

Relax the coverage requirements a bit, to make sure that PRs do not fail when coverage changes are very small. With this PR we allow:
- a 0.5% drop in overall coverage
- a 10% missed coverage in the patch
Of course, the goal should still be to increase the code coverage with every commit (or at least keep it the same), and attempt to have all your changes covered with test.
See discussion in #653 
lmfit: 1.0.1+33.g24c787e, scipy: 1.5.0, numpy: 1.19.0, asteval: 0.9.18, uncertainties: 3.1.4

TST: Add codecov configuration

---

doc/builtin_models.rst

This change fixes a small typo in the documentation.
I didn't test the change.
Have you

fix small typo on OscillatorModel

---

examples/example_sympy.py
requirements-dev.txt

This PR adds an simple example of using lmfit with sympy.
Have you
Not possible under windows currently.
- [x ] added an example?

Add sympy example

---

doc/builtin_models.rst
lmfit/models.py
tests/test_models.py

This PR adds a SineModel to models.py to fit sines. This was briefly discussed in https://groups.google.com/g/lmfit-py/c/uCF4tUT7DGs/m/YjtEuoJ1AwAJ
Also adds a base class that might be useful to add tests for models.py.
Python: 3.7.9 (default, Aug 31 2020, 12:42:55) 
[GCC 7.3.0]
lmfit: 0.9.15rc1+175.ged81916, scipy: 1.5.2, numpy: 1.19.1, asteval: 0.9.19, uncertainties: 3.1.4
Have you

Add sine model

---

.github/PULL_REQUEST_TEMPLATE.md
THANKS.txt
doc/whatsnew.rst

In preparation for a release in the future, this PR adds the changes in `master` since v1.0.1 to the release notes and acknowledges the new contributors in THANKS.txt. 
I doubt there will be any controversy regarding these changes, so I probably could have committed them directly - but just in case people have comments here is PR.
lmfit: 1.0.1+135.ge65e971, scipy: 1.5.4, numpy: 1.19.4, asteval: 0.9.21, uncertainties: 3.1.5
Have you

DOC: add changes in master branch to release notes

---

.github/CONTRIBUTING.md
doc/whatsnew.rst

Contributing guide is missing steps that are necessary to start working on `lmfit-py` project. This PR is adding missing steps.
Based on new instructions I am able to finish them.
Have you

Adjust contributing guide to mention all steps

---

lmfit/parameter.py

fix type on input parameter
- [x ] Documentation / examples
Have you

Fix name type in docstring

---

doc/confidence.rst

typo fix: fairy -> fairly

---

examples/example_detect_outliers.py

DOC: Fixed a typo

---

lmfit/confidence.py
lmfit/minimizer.py
lmfit/model.py
lmfit/parameter.py

Refactoring of if statements in `confidence.py`, `minimizer.py`, `model.py`, and `parameter.py`
```shell
Python: 3.8.12 (default, Nov 11 2021, 07:35:10) 
[Clang 13.0.0 (clang-1300.0.29.3)]
lmfit: 1.0.3, scipy: 1.7.2, numpy: 1.21.4, asteval: 0.9.25, uncertainties: 3.1.6
```
Have you

ENH: Refactoring of if-statements

---

lmfit/confidence.py
tests/test_confidence.py

The CI calculation now uses the root_scalar interface for root finding
and changes the default method to toms748. Additonally, caching of
probabilties is now used to speed up the calculation.
Improves the CI calculation by using some caching and using another root finding method.
Python: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
lmfit: latest master, scipy: 1.7.1, numpy: 1.20.3, asteval: 0.9.23, uncertainties: 3.1.6
Have you

[ENH] Confidence Interval improvements

---

lmfit/minimizer.py
lmfit/model.py
tests/test_model.py

This changes the coercion rules for the results of `minimizer` and data and independent variables for `Model`.
It addresses some of the discussion in #850.
Python: 3.9.15 (main, Nov 24 2022, 08:29:02)
[Clang 14.0.6 ]
lmfit: 1.1.0.post9+gd2ba8e9.d20230313, scipy: 1.9.3, numpy: 1.23.5, asteval: 0.9.29, uncertainties: 3.1.7
Have you

Un coerce independent vars

---

doc/Makefile
doc/model.rst
doc/whatsnew.rst

updating docs, getting ready to tag v 1.2.0rc1
Python: 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:24:27) [Clang 14.0.6 ]
lmfit: 1.1.0.post37+g97cf1f3, scipy: 1.10.1, numpy: 1.24.2, asteval: 0.9.29, uncertainties: 3.1.7
Have you

update whatsnew, add discussion of data coercion

---

lmfit/minimizer.py
tests/test_least_squares.py
tests/test_minimizer.py
tests/test_shgo.py

This fixes #896
Python: 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:17:34) [Clang 14.0.6 ]
lmfit: 1.2.1.post5+g980a5d1, scipy: 1.10.1, numpy: 1.24.3, asteval: 0.9.30, uncertainties: 3.1.7
Have you

Aborted least squares

---

.pre-commit-config.yaml
azure-pipelines.yml
doc/conf.py
doc/doc_examples_to_gallery.py
doc/model.rst
examples/doc_parameters_uvars.py
lmfit/parameter.py
pyproject.toml
tests/test_parameters.py

This fixes #962  and addresses some recent changes from `uncertainties` and `asteval` that were causing test failures.
Python: 3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:11:10) [Clang 16.0.6 ]
lmfit: 1.3.2.post1+g7b9837ed.d20240810, scipy: 1.14.0, numpy: 1.26.4, asteval: 1.0.2, uncertainties: 3.2.2.post7+gce16269
Have you

a few fixes: typos, updates for changes to uncertainties/asteval

---

doc/whatsnew.rst
lmfit/models.py
tests/test_model_saveload.py

fix: increase allowed number of knots in SplineModel to cover most use cases (close #985)
This PR resolves #985. I increased the number of knots for the spline model parsing function. As discussed in the issue, this should cover most use cases.
```
Python: 3.12.3 (main, Nov  6 2024, 18:32:19) [GCC 13.2.0]
lmfit: 0.0.post2880+g8cece2f, scipy: 1.15.1, numpy: 2.2.2, asteval: 1.0.6, uncertainties: 3.2.2
```
Have you

fix: increase allowed number of knots in SplineModel

---

lmfit/models.py

The [`DoniachModel` docstring](https://github.com/lmfit/lmfit-py/blob/467bb77be31a556715909f9be68cff911838aeef/lmfit/models.py#L1420-L1436) currently contains a formula for the line shape that is missing a square on one of the terms. The formula is
```
f(x; A, \mu, \sigma, \gamma) = \frac{A}{\sigma^{1-\gamma}}
\frac{\cos\bigl[\pi\gamma/2 + (1-\gamma)
\arctan{((x - \mu)}/\sigma)\bigr]} {\bigr[1 + (x-\mu)/\sigma\bigl]^{(1-\gamma)/2}}
```
and it displays as
However, the `(x-\mu)/\sigma` in the denominator needs to be squared to reflect [the implementation](https://github.com/lmfit/lmfit-py/blob/467bb77be31a556715909f9be68cff911838aeef/lmfit/lineshapes.py#L296-L311):
```python
arg = (x-center)/max(tiny, sigma)
gm1 = (1.0 - gamma)
scale = amplitude/max(tiny, (sigma**gm1))
return …
```

Fix formula in `DoniachModel` docstring
