lmfit/lmfit-py

lmfit/printfuncs.py
If two parameters had a negative correlation that was large then this is not displayed by `lmfit.printfuncs.fit_report`.
I.e. if `abs(correlation) > 0.1`, then the correlation should be printed.  This PR should fix the behaviour.
=> BUG: printfuncs was not printing large negative correlations

lmfit/model.py, tests/test_model.py
this adds a `_make_all_args` method to `CompositeModel`, so that `ModelFit.best_values` is correctly populated after a fit.
This addresses Issue #186.  
A test for non-empty `best_values` is added.
=> add _make_all_args to CompositeModel

lmfit/printfuncs.py
lmfit.printfuncs.fit_report is a nice way of print the results of a fit.  However, it sorts the dictionary before printing (line83):
parnames = sorted(params)
At the moment I am using parameter names ['p0', 'p1', ...., 'p10', 'p11', ...]
Consequently fit_report prints them in the order
p0
p1
p10
p11
p2
I would much rather we have an alphanumeric sort, or for the dictionary to remain ordered in the way they first got inserted in the dictionary
p0
p1
p2
p3
...
p10
p11
Is there a reason for this sorting?  Shouldn't we keep the natural ordering of the lmfit.parameters.Parameters object, or at least use alphanumeric ordering?
This PR uses alphanumeric sorting.
=> MAINT: lmfit.printfuncs.fit_report, using alphanumeric sort

lmfit/ui/__init__.py
Got the following error when trying to use lmfit in an ipython session.
```
/.../venv/lib/python2.7/site-packages/lmfit/__init__.py in <module>()
47 from .uncertainties import ufloat, correlated_values
48
---> 49 from .ui import Fitter
50
51 ## versioneer code
/.../venv/lib/python2.7/site-packages/lmfit/ui/__init__.py in <module>()
38     from .ipy_fitter import NotebookFitter
39     BaseFitter = BaseFitter
---> 40     MPLFitter = MPLFitter
41     Fitter = NotebookFitter
42
NameError: name 'MPLFitter' is not defined
```
=> fixes MPLFitter NameError when ipython is installed but matplotlib isn't

doc/parameters.rst, lmfit/parameter.py
This PR gives the Parameters class methods dump/dumps/load/loads to use a JSON representation of the Parameters.  
A few other minor fixes to Parameter class are included, for example that having 'min==max' now raises a ValueError.
=> add dump()/load() to Parameters class

lmfit/minimizer.py, lmfit/model.py, tests/test_nose.py
ravels output from Minimizer._residual and Model._residual, so that multidimensional fits can occur without the user having to flatten the data.
=> MAINT: ravel output from minimizer._residual, model._residual. Closes #205

lmfit/parameter.py
Add `pretty_print()` method to `Parameters` for nicer printing, since the default `OrderedDict` representation is  hardly readable.
=> Add pretty_print method to Parameters

doc/model.rst, lmfit/model.py
This PR does:
1. add a `yerr` argument to the ModelFit.plot_() methods
2. change the default for `yerr` when `weights` are used from `1/self.weights**0.5`  to `1/self.weights`.
3. change the default labels to *not* include the model name, and instead move the model name to the plot title.
I also added docs for the plot methods to the rst doc.
=> change default weighting in ModelFit.plot_() routines

lmfit/lineshapes.py
One could also change the `/2` to `/2.`, but this is better for py3.
=> Added __division __ to lineshapes, fixes a bug with expgaussian.

lmfit/asteval.py, lmfit/parameter.py
This *should* address #221, but I think it will need careful testing.
In this approach, asteval keeps a list of items to *not* try to deepcopy() (stuff it will be able to import from Python or numpy later), and Parameters.__deepcopy__() uses this list.
=> Limit deepcopy

lmfit/ui/ipy_fitter.py
This goes for issue  #232, how do I label that so they get connected?
This Pull requests fixes the broken widgets for the newest IPython Notebook 
Both py3 and py2 seem to work
There are still issues with overlapping widgets though, i have no idea on how to arrange them properly, seems they only have a width attribute...
=> Fixing Ipython Notebook widgets for Py3

lmfit/model.py
Two small fixes for plotting fit results.
1. `init_kws` keyword arguments is no longer ignored in `ModelResult.plot_fit()`
2. when determining more dense array for independent variable - indexing `[0]` and `[-1]` with `min()` and `max()`; this additionally makes this functionality compatible with pandas
=> Plot results

doc/builtin_models.rst, lmfit/lineshapes.py, lmfit/models.py
simple change to pseudo-voigt definition as per #229, so that the FWHM of the Gaussian and Lorentzian lineshapes are equal.  The `sigma` parameter is used un-altered for the Lorentzian, but altered for the Gaussian component.  The resulting FWHM of the sum is `2*sigma`.
=> fix pseudo-voigt definition as per github issue #229

lmfit/parameter.py, tests/test_params_set.py
This addresses issue #242, so that `Parameter.set()` works to set parameter attributes, even when already defined to have an `expr`.   It works in preliminary tests, but actual nose tests should be added.
It also adds the explicit setting of `_expr_ast=None` etc in order to address a problem with pickling and IPython uses, Issue #237
=> Parameter set() fixes

doc/fitting.rst, doc/model.rst, lmfit/minimizer.py, tests/test_itercb.py
This allows an iteration callback to return `True` (or any true value) in order to immediately abort a fit, addressing #241.  Results will be returned with the latest values for the parameters.  The fit success will be `False`, no error bars will be calculated, an `aborted` boolean attribute of the `MinimizerResult` will be set to `True`, and many fit statistics will have invalid (possibly `NaN`) values. That is, it should be darn obvious when a fit is aborted. 
Docs are updated to have a section on iteration callbacks, documenting this behavior, and a test has been added to ensure that aborting from  iteration callback works.
=>  allow iteration callback iter_cb to abort fit

doc/builtin_models.rst, lmfit/models.py
ExpressionModel shouldn't support `prefix` argument, and it should raise a Warning and being documented.  This addresses #256.
=> add warning and doc for prefix in ExpressionModel

doc/builtin_models.rst, lmfit/lineshapes.py, lmfit/models.py
A Moffat is commonly used in astronomy to describe point spread functions. However, the profile is generally useful for lines that have larger wings than a Lorentzian.
Not yet implemented: Better guess parameters.
FWHM expression in the Model.
I coudln't find out how to correctly add the FWHM expression in this case. As written in the documentation it is \sigma 2 \sqrt{2^{1/\beta}}-1.
It's the first time I use github, sorry if I did something wrong.
=> Added moffat function MoffatModel and appropriate documentation.

lmfit/asteval.py, lmfit/model.py, lmfit/parameter.py, tests/test_algebraic_constraint.py, tests/test_algebraic_constraint2.py, tests/test_model.py, tests/test_parameters.py, tests/test_params_set.py
Recent testing (#259) has revealed that `deepcopy` of Parameters is very slow. There are a couple of reasons for this.  Firstly, there was a significant period of time taken for determining symbols added by the user in _asteval.symtable, compared to when the interpreter is initialised.  This problem was solved using `set.difference`.
Secondly, there was a serious performance penalty in __deepcopy__ because whenever a `Parameter` is added to `_pars` the Parameters are forced to undergo a `update_constraints` via `__setitem__`. If 200 parameters are added then for each of the 200 parameters that you add you have to call `update_constraints`. `update_constraints` iterates through every parameter in a loop. This loop gets longer and longer everytime a Parameter is added. This problem has been …
=> MAINT: speedup Parameter.__deepcopy__ and asteval.__init__

examples/fit_with_analytic_jacobian.py
For a Gaussian and a Lorentzian analytic jacobians are implemented. Resulting fits show an improvement in the number of evaluations needed to find a solution.
=> Example how to use analytic jacobians together with built-in models.

conda-recipe/bld.bat, conda-recipe/build.sh, conda-recipe/meta.yaml
> Disclaimer: I am not sure if this will interest the lmfit community, but I needed it for my own project and thought that I'd share. If it's of no interest, feel free to close without merging. It will still be a good documentation of how to do this.
I created a conda recipe for lmfit using the [PyPi skeleton](http://conda.pydata.org/docs/build_tutorials/pkgs.html#build-a-simple-package-with-conda-skeleton-pypi) (on Windows, these commands must run with administrator privilege and after installing `conda install conda-build unxutils`):
```
>>> conda skeleton pypi lmfit --output-dir conda-recipe
```
To build the conda pakcage, from the root folder of the lmfit repo:
```
>>> conda build conda-recipe
```
To install, after building:
```
>>> conda install --use-local lmfit
```
Then check it …
=> Conda recipe

.travis.yml, doc/builtin_models.rst, doc/confidence.rst, doc/model.rst, lmfit/confidence.py, lmfit/model.py, lmfit/parameter.py, lmfit/printfuncs.py, tests/test_manypeaks_speed.py, tests/test_model.py
This started as a PR to add  `Model.conf_interval` to address #263, but sort of morphed into a general PR for 0.9.2, trying to address #262, better deal with #265, and even do some cleanup related to #261.
Features of this PR include
* `Model.conf_interval()` and `Model.ci_report()` added.
* `ci_report()` (for all confidence intervals) now shows differences from best-fit value by default, 
and has options of `with_offset=True, ndigits=5` to control whether the best-fit value is offset from other interval values, and how many digits to show.  It's also now in the documentation.
* make `Model.prefix` immutable,  make `Model.copy()` raise `NotImplemented`.
* `Model._param_names` is now a plain list (was `OrderedSet`, then `set`), which even further improves the performance of @licode #259 …
=> Model conf_interval

lmfit/parameter.py, tests/test_parameters.py
These changes speed up the `Parameter.value` attribute retrieval by a significant amount.
The following gists 
(unstreamlined _getval)
https://gist.github.com/andyfaff/a0158e26e663b9308899
and
(streamlined _getval)
https://gist.github.com/andyfaff/a3f4fc311a2c97c630fa
outline that the overhead from _getval is reasonably large. These modifications halve the time required to evaluate the `userfcn` in this example. A total speedup of ~31% should be achievable in Minimizer.__residual.
=> ENH: Streamline Parameter._getval

lmfit/parameter.py, tests/test_parameters.py
Peter Metz reports a problem with unpickling a `Parameters` instance. The problem can be reproduced with:
import lmfit
import pickle
p = lmfit.Parameters()
p.add('var_0', value=1)
p.add('var_1', value=2)
p['var_0'].expr = 'var_1'
pkl = pickle.dumps(p)
q = pickle.loads(pkl)
The Error arises because `var_0` has an expr that depends on `var_1`. When `p` is unpickled the unpickling process tries to retrive the value of `var_1` from the symtable, but it doesn't yet been added to the symtable.
Solution: add the symbols to the symtable first, then add the parameters.
=> MAINT: improve Parameters pickling support

lmfit/minimizer.py
This addresses #285 and #292 
scipy's OptimizeResult is (now? since when?) dictionary-like, so this checks for that and copies data into MinimizerResult.
This also fixes scalar_minimize() for the case of using a single variable, and makes sure that is a 1-element array.
=> scalar_minimize() fixes using scipy OptimizeResult

lmfit/parameter.py, tests/test_parameters.py
This adds a `copy()` method to Parameters, which makes an explicit deep copy.    This addresses issue #298.   The added test includes a parameter with a non-trivial constraint expression that is checked to ensure that the expression is evaluated correctly in the copy.
=> Copy params

lmfit/minimizer.py
addresses #301 by preventing a fit from aborting (from a user's iteration-callback) until at least len(fvars) (the number of variables parameters) iterations.
=> add check that fit cannot abort too early

lmfit/confidence.py, tests/test_confidence.py
This addresses #308, and an earlier messages on mailing list.
In `confidence_interval()`, a Parameter value (in `para.value`) may be either a plain `float` or a `numpy.float64`.  Plain `floats` do not have a `copy()` method.  
This PR simply takes `float` of the Parameter value for the starting value.
=> allow para.value to be plain float or np.float64

asv_benchmarking/asv.conf.json
The master branch of [asv](https://github.com/spacetelescope/asv) now allows you to install dependencies via pip, even if the `environment_type` is conda. This is relevant to lmfit because emcee is an optional dependency that is not installed via setup.py. This PR allows emcee benchmarking using asv (master branch 63b5fb and later)
=> MAINT: pip+emcee for asv

lmfit/model.py, tests/test_model.py
This appears to address #314 with a fairly simple rewrite and simplification of `Model.set_param_hint()`.  To be honest, I'm not sure I completely understand what the problem was.... but the problem seems fixed and the code more readable.
=> refactor Model.set_param_hint()

lmfit/parameter.py
Similar to #318.
`Parameters` has a `pretty_print()` which prints with the following style:
```
Parameters({
'p1_sigma': <Parameter 'p1_sigma', 0.03, bounds=[0.01:0.2]>, 
'p1_fwhm': <Parameter 'p1_fwhm', 0.0706446, bounds=[-inf:inf], expr='2.3548200*p1_sigma'>, 
'p2_sigma': <Parameter 'p2_sigma', 0.03, bounds=[0.01:0.2]>, 
'p2_fwhm': <Parameter 'p2_fwhm', 0.0706446, bounds=[-inf:inf], expr='2.3548200*p2_sigma'>, 
'p1_center': <Parameter 'p1_center', 0.3, bounds=[-0.1:0.7]>, 
'p2_center': <Parameter 'p2_center', 0.85, bounds=[0.5:1.1]>, 
'p1_amplitude': <Parameter 'p1_amplitude', 1, bounds=[0.01:inf]>, 
'p2_amplitude': <Parameter 'p2_amplitude', 1, bounds=[0.01:inf]>, 
'br_amplitude': <Parameter 'br_amplitude', 0.0001, bounds=[0:inf]>, 
'br_center1': <Parameter 'br_center1', 0.3, …
```
=> Improve pretty printing of Parameters

.gitignore, doc/conf.py, doc/parameters.rst, doc/whatsnew.rst, lmfit/confidence.py
This PR enables autodoc, napoleaon and mathjax sphinx extension and fix all warnings during build.
Seems like all the docs are correctly generated, so this can be a good starting point for a gradual switch to autodoc generated API docs.
=> Docs fixes

lmfit/models.py
This adds a constraint expression for `height` for several peak-like Models, including `GaussianModel` and `LorentzianModel`, similar to `fwhm`.   This will make both `amplitude` and `height` for these peak-like models available after after a fit and included (with estimated uncertainties when available) in the fit report.  I hope this will clarify the difference between `amplitude` and `height`.
As this is just a change to the reporting of results, no tests have been added or changed.
=> add 'height' expression for Peak-like models

doc/model.rst, lmfit/model.py
This PR adds docs entry for `Model.print_param_hints`.
=> Docs: add Model.print_param_hints to the sphinx docs

lmfit/model.py, tests/test_model.py
This fixes #328.    The essential change is to add the constraint expressions from model hints *after* the main model parameters have been added.  This avoids NameError exceptions that can arise if accessing a models parameters right after creation (and before the namespace is fully populated).  This is pretty similar to the situation that led to `param._delay_asteval`, but is now outside a single model (say, when making a composite).  
A test is added for this particular problem.  I'm not sure it's a completely general solution, and can believe other NameErrors when building models is still possible.
=> Fix eval errors with `Model.make_params()` and constraint expressions

lmfit/ui/basefitter.py
This fixes a simple error in lmfit.ui.basefitter.BaseFitter.guess.
Currently, if you try to use a model that does not implement a guess method, the code detects the NotImplmentedError and indicates guessing failed, but it also tries to update self.current_params = guess which raises an UnboundLocalError since guess never successfully got defined.
This can easily happen by simply creating a CompositeModel and not defining a guess method for it.
This pull request simply moves the assignment of self.current_params = guess such that it only happens if "guess" is defined. If guess fails, self.current_params shouldn't be updated anyway.
=> Minor fix for lmfit.ui.basefitter.BaseFitter in the case that model does not implement guess

lmfit/minimizer.py, tests/test_nose.py
Currently the `differential_evolution` option in `scalar_minimize` requires finite upper and lower bounds for all parameters. This PR removes that requirement. Instead finite upper and lower bounds are only required for those parameters that vary.
=> MAINT: de shouldn't need bounds if not varying

.travis.yml, doc/index.rst, doc/installation.rst, lmfit/__init__.py, lmfit/asteval.py, lmfit/parameter.py, lmfit/printfuncs.py, tests/test_model.py
This PR addresses Issue #334 
Dictionary comprehensions are changed to a style compatible with Python 2.6, i.e. `dict((key, value) for key in list)`. This should continue to maintain basic py26 compatibility for now, even if it is not officially supported. No additional tests should be required.
=> FIX: Changed dict comprehensions to style compatible with py26

lmfit/minimizer.py, tests/test_least_squares.py
Sorry for using the wrong repo for putting up the new branch. 
This PR adds support for new least_squares optimizer in scipy 0.17 with
inbuild support for bounds and robust likelihoods. For my problems the solver
generally is much faster than leastsq.
Not implemented yet is error estimation from the covariance matrices. This
can be done in another PR. Test failures are from 3.3 and 2.6, due to old scipy
versions.
=> Add support for least_squares, deleted deprecated methods.

LICENSE, doc/fitting.rst, lmfit/minimizer.py, tests/test_model.py, tests/test_nose.py
As discussed on ML, raise a `ValueError` if `userfcn` returns a non-finite number. This is because all of the scipy optimizers do not work in such a situation. However, the failure is insidious: the fit success is still `True` and the optimized parameters are just the initial guesses. Thus, the fit appears to work, when it is in fact not doing anything at all.
It was discussed on ML whether to raise an Error or a warning. My preference is for Error because I consider it to be an Error state. With a warning you might suspect that the situation isn't as bad as it really is.
=> ENH: raise error if userfcn returns non-finite number

INSTALL, doc/index.rst, doc/installation.rst, lmfit/__init__.py
This add deprecation notices for Python 2.6 and scipy 0.13 to the code and docs.
When merged, I propose this be tagged as 0.9.4rc1
=> Prepare 0.9.4

doc/fitting.rst, doc/parameters.rst
I've fixed some of the sphinx module names. This means that they will be linkable from other documentation sites.
=> DOC: fix module names

doc/model.rst
Add parenthesis to print statements in the docs and fix one typo.
=> Docs: use python3 print

README.rst
A missing colon was causing a code block to be rendered incorrectly. This pull request fixes this, corrects a few typos and adds a link to the Contributing.md file so it is easier to find.
=> Fix formatting of code in readme and correct typos

lmfit/minimizer.py, lmfit/model.py
Keyword arguments (to be passed to scipy.optimize functions) can be given during initializations of Minimizer object. However, Minimizer.minimize does not relays these arguments.
This also causes that the dict `fit_kws` passed to `Model.fit` was ignored.
=> Fix ignored kws in Minimizer.minimize

lmfit/model.py
As the subject says, small tweaks to create better default plots with `ModelResult.plot()`.
Changes:
- use `loc='best'` for legend positioning in `plot_fit` and `plot_residuals`
- remove title for bottom axis which is the same of the top axis and can overlap with other labels
- remove x-labels for top axis (we are sharing the x axis so they are redundant)
- return both figure and GridSpec. This is a convenience for easy tweaking the plot. As a side benefit, with this change calling `ModelResult.plot()` without capturing the return object will not display two duplicated figures anymore.
- Use a square figure by default using the default x-size of the figure also as y-size. Since we stack two plots vertically a square figure results in more legible plots in most cases. By using the default …
=> Plots: make a better default plot with ModelResult.plot()

lmfit/minimizer.py
This PR addresses Issue #378 
Instead of comparing ier only to 0, 5 or neither of them, which never resulted in result.message being "Fit succeeded." the changes lead to a comparison to five different cases, namely:
- ier is equal to 1, 2 or 3, which results in result.message = 'Fit succeeded.'
- ier is equal to 0, which results in result.message = 'Invalid Input Parameters. I.e. more variables than data points given, tolerance < 0.0, or no data provided.'
- ier is equal to 4, which results in result.message = 'One or more variable did not affect the fit.'
- ier is equal to 5, which results in result.message = self._err_maxfev % lskws['maxfev'] <-- as before
- ier is not any of the above, which results in result.message = 'Tolerance seems to be too small.'
Furthermore I changed the string …
=> Different fit messages depending on fit status code.

lmfit/lineshapes.py, lmfit/model.py, lmfit/models.py
this PR contains a few small, unrelated changes to Model and Models over the past couple weeks.  
A.  Add a damped-harmonic-oscillator model based on a model from PAN (In IDL, from NIST) used by some collaborators.
B. Increase the default estimate of the amplitude of a peak with `Model.guess`
C. Improve the `ensureMatplotlib` decorator to reveal the docstring and name of the decorated method.
D.  Allow Model to wrap certain function-like objects with `argnames` and `kwargs` arguments.  This is mostly for my X-ray spectroscopy framework xraylarch, which does generate such things (cause, you know, lmfit/python by themselves aren't slow enough!).
These should each have no actual impact on any existing tests or usage.
=> a few small changes to models.py and model.py

lmfit/model.py, tests/test_model.py
This PR addresses Issue #384, by having parameter values passed into Model.make_params() overwrite values that may otherwise be set by a parameter hint.
A simple test is included.
=> allow values for param hints to be overwritten by explicit setting in Model.make_params()

lmfit/parameter.py, tests/test_nose.py, tests/test_params_set.py
This PR fixes the set function of the Parameter class, which currently inadvertently affects the max/min/expr settings. Issue and solution discussed in #389.
=> FIX: set function of Parameter class

lmfit/minimizer.py
Use the zero-th temperature from the PTsampler to calculate parameter estimators, as indicated by http://dan.iel.fm/emcee/current/user/pt/
=> MAINT: use the zeroth PTsampler temp in emcee

lmfit/minimizer.py, lmfit/parameter.py, tests/test_parameters.py
this addresses #394, and explicitly formats the result for  `Parameter.dumps()` so that a working copy can be reconstructed from `Parameter.loads()`
A simple test is included.
=> fix Parameter.dumps()/ loads()

lmfit/parameter.py
Very small fix in the deepcopy method.
The user_value attribute in the Parameter class could be used for custom/user defined attributes assigned to each parameter. Ensure that this attribute will persist during a deepcopy call and adapt therefore the deepcopy method in the Parameters class.
=> Add user_value attribute to the deepcopy routine in the Parameters class.

.travis.yml, doc/installation.rst, lmfit/__init__.py, requirements.txt, setup.py
This PR partly addresses #398 and now `scipy` version 0.15 or above is required for `lmfit` and this version is used now for the Travis CI builds. In addition, testing against Python 3.6 is also added since it turns out that #397 isn't blocking this (i.e., `inspect.getargspec()` is still present). Finally, the logic for which Python versions are supported is moved to the `setup.py` such that it will not install with unsupported version.
=> Bump minimum scipy version to 0.15

lmfit/minimizer.py, tests/test_nose.py
Fix the `result.lnprob` attribute when using the `~emcee.PTSampler`.
The confusion comes from emcee when `sampler.lnprobability` has a shape (ntemps, nwalkers, nsteps) for the `~emcee.PTSampler`, while the `~emcee.EnsembleSampler` returns a (nwalkers, nsteps).
=> Fix returned logp when using the PTsampler

lmfit/parameter.py, tests/test_parameters.py
This addresses #400, and changes `Parameter.set()` to set the `value` property, not just the internal value in `_val`.  The difference is that the `Parameters` symbol table is also updated with the property, so that dependent parameters using constraint expressions will be updated as soon as they are evaluated.  
A test is included.
=> Param set symtable

.travis.yml, doc/_templates/indexsidebar.html, doc/bounds.rst, doc/builtin_models.rst, doc/confidence.rst, doc/faq.rst, doc/fitting.rst, doc/index.rst, doc/installation.rst, doc/intro.rst, doc/model.rst, doc/parameters.rst, doc/sphinx/theme/lmfitdoc/layout.html, doc/support.rst, doc/whatsnew.rst, lmfit/__init__.py, lmfit/confidence.py, lmfit/minimizer.py, lmfit/model.py, lmfit/models.py, lmfit/parameter.py, lmfit/printfuncs.py, requirements.txt
As discussed in #402 here are some updates to docs and docstrings. I tried to make them a bit more consistent and hopefully followed the numpydoc / napoleon conventions... Probably the file `lineshapes.py` could use some work, I haven't touched that one.
In addition to docs/docstrings, this PR contains the following other changes:
-  correct initialization of `user_data` in the Parameter class
- updating Travis to the newest SciPy version
- some minor style fixes
I am sure that there is more room for improvement, but this is probably as much as will happen from my side before the release of 0.96. @newville, please let me know what you think and if there is anything else you'd like to happen!
=> docstring / doc changes for 0.96

lmfit/model.py
This PR addresses Issue #397: inspect.getargspec() is deprecated in Python 3. 
According to [the documentation](https://docs.python.org/3/library/inspect.html), the function `inspect.getfullargspec()` will not be removed and it's advertised as a drop-in replacement for `inspect.getargspec()`.
This PR changes the logic in `model.py` such that it will first try `inspect.getfullargspec()` (present in PY3) and otherwise will fallback on `inspect.getargspec()`. The only difference in the return values we care about (see [the documentation](https://docs.python.org/3/library/inspect.html)) is that `keywords` (for argspec) has been renamed to `varkw` (for getfullargspec). 
No tests were changed or added since the current tests will already checks whether proper results are obtained from …
=> use inspect.getfullargspec() in Python 3, otherwise inspect.getargspec()

examples/lmfit_brute.py, lmfit/minimizer.py, tests/test_brute_method.py
This PR includes two updates to the brute force method:
1) fix the issue that pickle doesn't work with the `MinimizerResult` when the brute force method is used (related to the use of a `namedtuple`).
2) add a function to visualize the result of the grid search (inspired by the way the `corner` package can be used to visualize the results of the `emcee` method). Comments and suggestions on the actual code are welcome, as well as where to put it; right now I added it into a file called `plotfuncs.py`.
Before a possible merge, it will need some updates to the documentation. Example has been updated together with the resulting output file (`examples/results_brute.pdf`), and no tests were added or changed.
=> Updates to brute force method

lmfit/models.py, tests/test_model.py
I found that `Model.eval_components()` fails with a `ConstantModel`.   This fixes that error, and adds a test.
=> Fix eval_components() with ConstantModel

lmfit/models.py, tests/test_model.py
Currently the ExpressionModel cannot be part of a CompositeModel as the merging logic of param_names rejects to add lists and sets. This change would fix this issue.
=> param_names in ExpressionModel should be list

lmfit/minimizer.py
this PR adds some of the missing attributes to the `MinimizerResult` when using the `brute` method. Currently the `fit_report` doesn't work. In addition, I would like to have this attributes present irrespective of the fitting method used so that I can use them in my downstream fitting program.
=> add missing attributes to MinimizerResult when using brute method

doc/model.rst, examples/doc_model_with_nan_policy.py, lmfit/minimizer.py, lmfit/model.py, tests/test_model.py
This is an attempt to resolve #423.  
Here, `Model` gets a `nan_policy` argument, that matches that for `Minimizer`.  The older 'missing' options are still supported, but `nan_policy` should be preferred.   
In addition, `nan_policy` can now be specified at `Model.fit()` (or `ModelResult.fit()`) time, instead of only when creating a Model. 
The check for pandas and use of 'pandas.isnull` vs `numpy.isnan` is now moved to `minimize.py`, and used for all `minimize` uses.  There is still a sort-of-question of how to handle the difference of `~np.isfinite` and `np.isnan` when dealing with pandas Series.   So, this PR also makes a subtle change to `Minimizer._residual()` that the nan policy is applied after the user-callback, and after doing "np.asarray()" and "ravel()".  I believe that will …
=> rationalizing Model "missing" and "nan_policy"

lmfit/models.py
Add limit to Pearson7 expon to prevent nan error when approaching normal distribution
On my system a max above 171 creates a nan error when fitting a normal distribution such as:
`from lmfit.models import Pearson7Model
from scipy.stats import norm
mu = 0
variance = 1
sigma = np.sqrt(variance)
x = np.linspace(mu - 6*sigma, mu + 6*sigma, 100)
y = norm.pdf(x, mu, 1)
mod = Pearson7Model()
pars = mod.guess(y, x=x)
out = mod.fit(y, pars, x=x)
`
So, limit is set to 100 to keep things nice and even.
=> Add limit to Pearson7 expon to prevent nan error when approaching normal distribution

lmfit/asteval.py, lmfit/astutils.py, lmfit/models.py
Add fwhm and height parameters to Pearson7 model.
This requires adding gamfcn to asteval which has been implemented similarly to the numpy attribute importing.
=> Add fwhm and height parameters to Pearson7 model

examples/benchmark_fit.py, examples/example_derivfunc.py, examples/example_lbfgsb.py, examples/fit_with_analytic_jacobian.py, examples/fit_with_bounds.py, examples/plot_fit.py, examples/plot_fit2.py
The example files didn't work because it assumed that `fit.plot()` returns a Matplotlib `Figure`, bit it returns a tuple with the Matplotlib objects (´Figure´, ´Gridspec´).
This pullrequest simply assign the ´Gridspec´ to the variable ´gridspec´, and ´Figure´ to the variable ´fig´, so that the examples work again.
Also replace print-statements with print-functions, since they work in both Python 2 and 3.
Finally I removed the backend-setting, since the Qt4Agg is not available in all installations.
=> Tuple assignment fixed bug causing crash in examples, and some minor changes.

INSTALL, README.rst, doc/builtin_models.rst, doc/confidence.rst, doc/constraints.rst, doc/faq.rst, doc/fitting.rst, doc/index.rst, doc/installation.rst, doc/intro.rst, doc/model.rst, doc/parameters.rst, lmfit/confidence.py, lmfit/minimizer.py, lmfit/model.py, lmfit/models.py, lmfit/parameter.py, tests/test_model.py
In addition to #432, there were examples in the documentation that didn't work or where the output was -slightly- different with the current version of lmfit. In this PR, there are additional updates to the documentation and docstrings.
A few things that I am a bit confused about and that probably should be resolved in this PR before merging are the following:
In ```models.py``` in the ```__init__``` there is parameter ```name``` for most model classes, which therefore also shows up in the documentation. It seems to me however, that this will never be used as it is not updated in ```kwargs```. If that's indeed the case, should we just remove this?
In addition, all the models still use ```missing```, which is according to the documentation set to None - however it seems to me that with …
=> Documentation updates

.travis.yml, INSTALL, doc/installation.rst, lmfit/minimizer.py, requirements.txt, setup.py, tests/test_least_squares.py
The commit in this PR does the following:
* remove testing for Python 3.3, which reached EOL
* test for current versions of SciPy/NumPy for all Python versions
This will install the latest version of scipy/numpy available in conda for a certain Python version. Currently, it uses numpy 1.13.3 and scipy 1.0.0 (PY27, PY35 and PY36) and numpy 1.11.3 and scipy 0.18.1 fo PY34.
* test for minimum required SciPy/NumPy for Python 2.7 and latest Python 3 version
To limit the number of builds I think it should be sufficient to test the minimum required version of numpy/scipy with PY27 and -ideally- the latest PY3 release. For PY27 we can do both builds with the minimum scipy/numpy versions, but for PY36 the requirements can only be satisfied for numpy. Therefore, the minimum scipy version is tested …
=> update configuration for Travis testing

lmfit/lineshapes.py
some simple fixes to dho() lineshape to avoid NaNs.   Also unifies the value used for "tiny" used to avoid divide-by-zero and related floating point errors.
=> fix to dho() model, uniform "tiny" value for lineshapes

lmfit/model.py
Hello, new contributor here.
I've extended the `eval_uncertainty` method in the `ModelResult` class to permit changes to the independent variables. The purpose is to be able to evaluate the uncertainty (confidence band) for the model at arbitrary values of the independent variable. Previously, only uncertainties at the original independent variable values would be evaluated.
Detailed changes:
* don't overwrite ModelResult.userkws
* ensure fjac ad df2 are correct size if independent variable is updated
* ensure original ModelResult.ndata is not changed for computing t.pp
=> Evaluate uncertainty for arbitrary independent variable value

tests/test_height_fwhm.py, tests/test_saveload.py
The testsuite fails (on my box), because numpy does not find the example data referenced by relative paths.
```
.................................../home/erich/eigeneSkripte/archPackages/python-lmfit/src/lmfit-py-0.9.8/lmfit/minimizer.py:1563: RuntimeWarning: invalid value encountered in log
_neg2_log_likel = result.ndata * np.log(result.chisqr / result.ndata)
......E......S.........SS....S...S..........S.........S.........S.........S.........S.........S.............S.........................................capi_return is NULL
Call-back cb_calcfc_in__cobyla__user__routines failed.
.......................E..
======================================================================
ERROR: test_height_fwhm.test_peak_like
---------------------------------------------------------------------- …
```
=> tests/test_height_fwhm.py, tests/test_saveload.py: use absolute paths

.travis.yml, lmfit/model.py, lmfit/models.py, tests/test_model.py
This PR allows Model prefixes to be changed after the Model has been created.  Resetting the prefix includes updating the parameter hints to be evaluated correctly.
=> Prefix renames

lmfit/printfuncs.py
This (tries to) address #458 by fixing `printfuncs.gformat` for values near 1.e-4.
=> fix formatting error for values near 9.99e-5

lmfit/printfuncs.py
this PR makes some improvements to the output of ```fit_report``` (mainly regarding white spaces), in addition to a few PEP8 style changes. In particular, it improves how the ```Correlations``` are shown; it doesn't use a fixed-width anymore but takes into account the maximum length of the names of the correlated parameters. This will avoid the excessive whitespace to fill up to 25 characters and also align correctly when the label is actually larger than 25 characters.
If this seems like a worthwhile change, I can re-run the examples and update the output in the documentation.
=> Improve output of fit_report

lmfit/printfuncs.py
this changes the fit report to use `gformat()`  for fit statistics.  
I regularly see reduced chi-squares that are very small for 'f' format, and seeing more than 2 digits would be nice.
=> use gformat for fit statistics

lmfit/minimizer.py, tests/test_confidence.py
continuing from the [mailinglist](https://groups.google.com/forum/#!topic/lmfit-py/Ywqx68tZ4zs).
this PR makes the reported number of function evaluations ```nfev``` consistent between ```lmfit``` and ```scipy.optimize.*```. Now in the methods that require it, the value of ```result.nfev``` is initialized with a value to correct for "pre-fit" calls to the objective function. In cases where we call the ```__residual``` function after the fit, it also correct for that. In addition, calls to ```__jacobian``` are not added to ```nfev``` anymore; consistent with the optimizers in ```scipy```. A small fix to a test is also included, since the current ```nfev``` count for ```leastsq``` is two smaller. For ```least_squares``` no correction is done, but it just takes the number reported by the …
=> consistent nfev

lmfit/minimizer.py
The test ```test_itercb.py``` fails with the newest version of ```scipy``` with the exception  ```ValueError: The array returned by a function changed size between calls.``` (as discussed in #465).
This PR attempts to address this by raising an AbortFitException instead of returning ```None``` when a fit is aborted by the callback function. Currently this exception is only handled in the ```leastsq``` function (and the test passes now), but can easily be extended to the other minimizers. However, before doing so I'd like to get some feedback to make sure whether this is the preferred solution to the problem and if I am missing something with this approach.
=> Raise an AbortFitException when fit is aborted by user callback

doc/fitting.rst, doc/whatsnew.rst, lmfit/minimizer.py, tests/test_basinhopping.py
As discussed in #440, including some more global optimization algorithms wouldn't hurt. This PR adds support for the ```basinhopping``` algorithm as implemented in ```scipy```. 
It passes bounds to the underlying optimizer (i.e., the default optimizer is now ```L-BFGS-B``` since we're using bounds) and it uses the ```accept_test``` callable to accept only steps that stay within the parameter bounds.
In addition, one test is included to make sure that the implementation in ```lmfit``` gives the same results as directly calling ```scipy.optimize.basinhopping```. And just because I noticed, I also update the name of the example for the ```brute``` method.
=> Add support for scipy.basinhopping

lmfit/model.py
This addresses #470 by allowing (nearly) any exception from trying to import matplotlib.
=> tolerate nearly any exception when trying to import matplotlib

lmfit/parameter.py
this simplifies the code of `parameter.isclose()`, used to tell if `Parameter.max` and `Parameter.min` are the same.  
It also avoids errors for large integers as seen on the mailing list (https://groups.google.com/forum/#!topic/lmfit-py/OqdMQ3wEdVc).
=> simplify and fix corner-case errors testinf closeness of large integers

lmfit/minimizer.py, tests/test_ampgo.py, tests/test_basinhopping.py, tests/test_brute_method.py
This PR adds a function to the MinimizerResult class to calculate the fitting statistics. With the addition of more solvers there is currently quite a bit of code duplication to do this. It assumes that every solver will still calculate/set ```result.residual``` correctly before calling the function.
In addition, the tests for brute/basinhopping/ampgo were updated. When fitting to a function one should compare the output from the ```scipy``` solver to ```result.residual``` not ```result.chisqr```.
=> add function to calculate fitting statistics

MANIFEST.in
I turns out that I forgot to add the ```*.ipynb``` files in the example directory - this fixes that. In addition, for some reason there are a few spurious left-over files in the ```examples``` directory when downloading from PyPI (e.g., ```A.py``` and ```so1.py```). I don't really understand where they come from, but removing the ```dist``` directory and running ```python setup.py sdist``` does fix it. 
Not a big deal and no need to upload a new file to PyPI, but let's fix this now before I forget...
=> add missing Jupyter notebook examples

lmfit/minimizer.py, tests/test_covariance_matrix.py, tests/test_model.py
This PR contains some groundwork in preparation for working on Issue #169, in particular:
* do the MINUIT transformation to the external parameter space directly on the covariance matrix
* apply this method in ```leastsq``` and use the covariance matrix from ```scipy.leastsq``` instead of calculating it again from ```fjac``` and ```ipvt```.
* re-factor the code for calculating parameter uncertainties/correlactions into a method
* fix a test: now ```stderr``` is ```None```, when ```result.errorbars``` is ```False```
* add a (non-exhaustive) test to make sure the covariance matrix and uncertainties/correlations are still the same (compare to version 0.9.10). 
In the first commit (f3648f9), I explicitly assert-ed whether the "old" and "new" methods to get the transformed covariance matrix …
=> Transform covariance matrix and refactor code for parameter uncertainties/correlations

lmfit/jsonutils.py, lmfit/parameter.py, tests/test_parameters.py
This PR does a better job of initializing a Parameter value, especially for bounded expressions. Basically, in the case where `value` is `None`, it assigns that to `-Inf` sooner.
A test is included.
=> Parinit bounds

.travis.yml
Travis CI has some issues with Python 3.7 and does not support the ```3.7``` version; however, ```3.7-dev``` works. This installs an old, pre-release version of Python (alpha4), but since we use ```conda``` anyway, it doesn't really matter for us. This workaround allows us to test Python 3.7 right now and we can change to ```3.7``` when Travis officially supports it.
=> Add python3.7 to Travis CI testing

lmfit/parameter.py, tests/test_parameters.py
A test is not needed since all this does is clear the list `parameter._expr_eval.errors` **before** parsing a newly given parameter expression string. The only use of this list is to compare if its length is >0 **after** trying to parse the expression. If it is, an exception is raised.
For more detail, see #486.
=> fixed #486

lmfit/model.py, tests/test_saveload.py
This addresses #491 by making sure that `data`, `weights`, and `init_params` are properly recovered from a saved modelresult.
=> Fix load modelresult

lmfit/minimizer.py, tests/test_least_squares.py, tests/test_nose.py
This PR adds the calculation of parameter uncertainties/correlations to the ```least_squares``` method. 
I am still working on using ```numdifftools``` to get the covariance matrix for the scalar_minimizers, which works for non-bounded fits, but does not yet work correctly when bounds are specified... to be continued. Nevertheless, if the optimizer provides enough information already to calculate the covariance matrix, as is the case for ```least_squares``` (which gives the Jacobian) there is no need to use any external algorithms. A test is added to confirm that the results are the same as obtained for ```leastsq```.  
In addition, ```results.errorbars``` is set to ```True``` in the function ```_calculate_uncertainties_correlations```. Finally, a unrelated DeprecationWarning is addressed …
=> calculate uncertainties in least_squares method

lmfit/jsonutils.py, lmfit/model.py, lmfit/parameter.py, tests/test_parameters.py
This PR attempts to address #507.    The main idea is to add a `usersyms` keyword to `Parameters.__init__()` to make it easier to add custion functions and symbols, as with:
```python 
def myfun(x):
return x*x
params = Parameters(usersyms={'myfun': myfun})
```
This works failrly simply itself (and a test is added based on the simple example in #507).  With this change, we could probably deprecate the `asteval` argument to `Parameters.__init__()`. 
However, a complication arises in `dump/load` of Parameters that contain an added reference to a numpy ufunc (and, to be clear we always do this).  Previously we were sort of cheating (when dill was not available) by assuming we knew which functions and ufuncs we were adding to the asteval interpreter.   When a user adds a user symbol, we really …
=> Add `usersyms` to Parameters() initialization

.travis.yml, doc/fitting.rst, doc/installation.rst, lmfit/minimizer.py, lmfit/model.py, tests/test_covariance_matrix.py
This PR addresses Issue #169 and allows for the estimation of parameter uncertainties and correlations for minimizers other than ```leastsq``` and ```least_squares```. In order to do so, it requires the ```numdifftools``` package to be installed.
A parameter, ```calc_covar```, is added to the Minimizer and Model classes (default is True) and can be set to False if one does not want to calculate the covariance matrix. Test are added to check whether everything works as intended for a simple case.
To avoid failures of existing tests, it seems a requirement that ```result.residual``` has a length greater than the number of fitting parameters. I think that's correct, but would appreciate others to take a look at this and the rest of the code (in particular the Model class). Additionally, I …
=> add numdifftools to estimate parameter uncertainties/correlations

doc/builtin_models.rst, lmfit/lineshapes.py, lmfit/models.py
This PR adds DoubleLorentzianModel. 
The changes include: 
* addition of ``double_lorentzian()`` lineshape
* addition of ``DoubleLorentzianModel``
* addition of the model to the list of peak-like models in the docs.
I haven't found any tests for Lorentzian model, please let me know if those exist / are needed.
Also, no example for the new model was added.
=> Add Double Lorentzian Model

.travis.yml, INSTALL, doc/installation.rst, lmfit/minimizer.py, requirements.txt, tests/test_basinhopping.py
This PR bumps the required SciPy version to 0.19, which prompted the following changes:
- keyword ```seed``` is present for the ```basinhopping``` method
- keyword ```atol``` is present for the ```differential_evolution``` method
In addition:
- several (newer) algorithms are present in newer SciPy that accept the ```hess``` and ```jac``` keywords, this list is updated
- SciPy v1.2 added supports parallelization in the ```differential_evolution``` methods, this is supported now in ```lmfit``` as well. Two additional keywords (```updating``` and ```workers```) are added; see the commit message or SciPy documentation for more information. I'll review the need for extra test as part of the switch to ```pytest```.
The presence of the ```seed``` keyword simplifies the tests in …
=> Bump minimum SciPy version and support parallelization in DE

lmfit/model.py
This delays the import of `matplotlib.pyplot` until as late as possible -- inside the `plot_*` routines.
Addresses #528.
=> delay import of matplotlib.pyplot until actually needed

lmfit/minimizer.py
This addresses #535 by explicitly calling the residual function one last time with the best-fit values.
Because the differences will typically by at the 1.e-7 level, I'm reluctant to try to add an automated test for this, but if anyone has an idea for how to do that well, suggestions would be welcome!
=> force final evaluation of residual with best-fit parameter values

examples/example_reduce_fcn.py, lmfit/minimizer.py, lmfit/model.py
In lmfit 0.9.8 the ```missing``` argument was deprecated in favor of ```nan_policy```, for consistency with the ```Minimizer``` class. Similarly, ```drop``` was deprecated in favor of ```omit``` (and additional code for backwards compatibility was added). 
This deprecation was, however, only done in the documentation and no warning was shown when these keywords/arguments were still being used. This PR adds an explicit ```FutureWarning``` (which is as far as I can tell the appropriate thing to do if the message is intended for end-users) about it and states that these things will be removed in the next release (we can get rid of the compatibility-code and clean up the function signatures and docstrings).
In the tests we still use some of this ourselves and that should be cleaned up, but I …
=> Show FutureWarning about deprecation of "missing" and "drop"

.pre-commit-config.yaml, lmfit/printfuncs.py
This more or less reproduces #537 to report why errorbars may have not been estimated.
It also removes the isort `pre-commit` hook -- I was having odd troubles with this.  I also sort of disagreed with at least one of its choices.   It looks like there are other similar pre-commit hooks, so perhaps this could be revisited.  For now, the feature is more important than the linter choices.
=> Report for noerrorbar

lmfit/models.py
As shown in Issue #539 the parameters are not updated immediately after using the ```guess``` method for the built-in model (at least for ```VoigtModel```). Adding a ```pars.update_constraints()``` at the beginning of the ```update_param_vals``` function resolves this. 
Python: 3.7.2 (default, Jan  6 2019, 12:34:03)
[Clang 10.0.0 (clang-1000.11.45.5)]
lmfit: 0.9.12+69.gc405af5, scipy: 1.2.1, numpy: 1.16.2, asteval: 0.9.13, uncertainties: 3.0.3, six: 1.12.0
Have you
=> FIX: update parameters/constraints after guess in built-in models

.travis.yml, README.rst, lmfit/model.py, lmfit/printfuncs.py, tests/test_saveload.py
This should address #534 by creating a new MinimizerResult when loading a ModelResult with `ModelResult.loads`.    It is not finished, definitely needing a test similar to the offending script of #534.
=> add MinimizerResult when loading ModelResult

lmfit/minimizer.py, lmfit/model.py, lmfit/parameter.py, lmfit/printfuncs.py, tests/test_fitreports.py
This is an alternative to #524 that ought to merge more seamlessly (ie, I started with current master). 
It includes the fixes suggested by @reneeotten in the discussion there, putting the actual code in `printfuncs.py`, replacing `user_value` with `init_value` and adding `brute_step` if used.
This also includes a basic test that the html_reprs are created for a non-trivial case.
Hopefully, we can merge this and tag 0.9.13 within a couple days. ;)
=> alternative html_repr 

doc/fitting.rst, lmfit/lineshapes.py, lmfit/minimizer.py, lmfit/models.py, lmfit/printfuncs.py, tests/test_covariance_matrix.py, tests/test_lineshapes_models.py, tests/test_shgo.py
SciPy v1.2 introduced two new global optimization algorithms and these should be supported in lmfit as well (see #527). This PR adds the ```shgo``` (simplicial homology global optimization) method.
Tests were added to check make sure the implementation in lmfit gives the same result as calling ```scipy.optimize.shgo``` directly, using the example in thes SciPy function docstring. It seems to me there *might* be an upstream issue when using bounds at ```0``` or ```None```, but I'll need to narrow that down a bit more to make sure that's indeed the case. The tests in ```test_covariance_matrix.py``` and a few others I tried myself did not work when a boundary was exactly set to zero (throwing an error from ```scipy/optimize/_shgo_lib/triangulation.py```). Replacing the ```0``` with a very …
=> SHGO algorithm

.pre-commit-config.yaml, .travis.yml
Commit e1f71975ff37bdb7cace6902e9d384ae1c398710 added running ```coverage``` as part of Travis CI. Since then the test-suite is run twice for every Python version (see, for example, [here](https://travis-ci.org/lmfit/lmfit-py/jobs/527066018)). Admittedly, setting up the conda environment takes most of the time anyway, but running the tests first with ```pytest``` and then again with ```coverage run --source=lmfit -m pytest``` is not really necessary ;) This PR removes the first call of ```pytest```.
In addition, it updates the ```pre-commit``` hook for ```pyupgrade``` to version 1.16.3.
lmfit: 0.9.13+17.g81d88f8, scipy: 1.2.1, numpy: 1.16.3, asteval: 0.9.13, uncertainties: 3.0.3, six: 1.12.0
Have you
=> MAINT: don't run test-suite twice on Travis CI

doc/parameters.rst, lmfit/parameter.py, tests/test_parameters.py
This PR is in reference to the discussion here: https://groups.google.com/forum/#!topic/lmfit-py/pJWdxzYRGqI
Expressions derived from parameter values are often added to a Parameters() object using params.add("name", expr="expression"). These expressions can contain common numpy functions, user-defined functions, and parameter values. During a fit, they are evaluated every iteration. 
If this updating behavior is not desired, an expression can be evaluated post-fitting using the parameter values directly using p = params.valuesdict(). However, there is currently no public method to retrieve user-defined symbols from the object. 
This PR addresses this point by allowing the user to evaluate arbitrary expressions in the Parameters object's namespace via the params.eval() method. A test for …
=> Params eval

doc/fitting.rst, lmfit/minimizer.py, tests/test_covariance_matrix.py, tests/test_dual_annealing.py
This PR adds the ``dual_annealing``` algorithm that was introduced in ```scipy``` v1.2 (see Issue #527)
lmfit: 0.9.13+29.g63369d3, scipy: 1.2.1, numpy: 1.16.3, asteval: 0.9.13, uncertainties: 3.0.3, six: 1.12.0
Have you
=> Add dual_annealing algorithm

.pre-commit-config.yaml, lmfit/minimizer.py
The ```brute``` code has undergone some changes in ```scipy``` v1.3 (I'll make a PR to support the new parallelization later). Now, the tests fail because there is no need anymore for the "pre-fit" correction of ```nfev```. I have changed the code in the ```brute``` function accordingly (only do the correction for SciPy <= 1.2). Additionally, I have updated the ```pre-commit``` update hooks.
lmfit: 0.9.13+30.gca4f853.dirty, scipy: 1.3.0, numpy: 1.16.3, asteval: 0.9.13, uncertainties: 3.1, six: 1.12.0
Have you
=> Fix brute method/test

lmfit/printfuncs.py, tests/test_parameters.py
`lmfit.printfuncs.params_html_table` is prone to unhandled ZeroDivisionError exception in the case where one of the parameters is fixed to zero. I added an if statement to check for this possibility, so to avoid this potential issue.
Python: 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)]
lmfit: 0.9.13+23.g579f2a5, scipy: 1.2.1, numpy: 1.16.2, asteval: 0.9.13, uncertainties: 3.0.3, six: 1.12.0
Have you
- [x ] squashed/minimized your commits and written descriptive commit messages?
It's a bit hard to write a test case because I can not define parameter with stderr not None. This property only emerges at the output of minimize. I would be happy to add test coverage otherwize. 
In any case, one should not divide without …
=> Fix Division by Zero problem

lmfit/minimizer.py, tests/test_nose.py
Currently, the ```emcee``` method does not set the ```.method``` attribute when using ```is_weighted=False``` and fails when doing ```lmfit.report_fit(<out>)``` with:
```
AttributeError: 'MinimizerResult' object has no attribute 'method'
```
The issue is that when is_weighted=False, ```result = self.prepare_fit(params)``` gets (correctly) called again, which re-initializes the ```MinimizerResult```. Since we did set ```result.method = 'emcee'``` a few lines earlier, that attribute is now undefined.
This PR fixes that and adds a regression tests.
lmfit: 0.9.13+34.gbbdda29, scipy: 1.3.0, numpy: 1.16.3, asteval: 0.9.13, uncertainties: 3.1, six: 1.12.0
Have you
=> FIX: always set result.method for emcee

lmfit/parameter.py, tests/test_parameters.py
Addresses #560 
This looks for NameError on adding parameters and tries again (up to a few times) to try to resolve NameErrors when adding parameters with valid but out-of-order constraint expressions.
- [ x] Bug fix
Have you
- [ x] verified that existing tests pass locally?
- [ x] added or updated existing tests to cover the changes?
=> more careful adding of parameters to handle out-of-order constraint expressions

.pre-commit-config.yaml, lmfit/minimizer.py
In SciPy v1.3 the ```brute``` method learned how to evaluate the search grid in parallel and gained a new keyword ```workers``` for this feature. This PR adds that keyword to the ```brute``` method in lmfit, but will only use it when scipy >= 1.3 is installed. Requirement here is of course that ```func``` can be pickle-d.
I added the keyword to the end of the function in order not to break backwards compatibility. In all other methods calling ```scipy``` minimizers the function arguments in lmfit are always ```def method(self, params=None, **kws)```, except for ```brute```. I initally made this decision since ```Ns``` was needed for calculation of the boundaries within the function and the ```keep``` keyword was also not a ```scipy.brute``` argument. Does it make sense to add …
=> Parallellization of brute force method 

setup.py
Currently, the requirements do not end up in the json meta-data on PyPI which limits the usability of tools that rely on it. For example, the tool [upt](https://framagit.org/upt/upt) that we are currently exploring to help with packaging for MacPorts, does not report any dependencies.
Apparently, the information is computed locally when generating the PyPI package and, therefore, might depend on how this is exactly done. Nevertheless, explicitly listing the dependencies should resolve this.
lmfit: 0.9.13+47.g3e45ad8, scipy: 1.3.0, numpy: 1.16.4, asteval: 0.9.14, uncertainties: 3.1.1, six: 1.12.0
Have you
=> Explicitly add install_requires in setup.py

lmfit/models.py
This addresses #566 and message https://groups.google.com/forum/#!topic/lmfit-py/HgPt_EVXQfo
lmfit: 0.9.13+47.gc5efd5c, scipy: 1.2.1, numpy: 1.16.4, asteval: 0.9.14+1.g14b5e13.dirty, uncertainties: 3.0.2, six: 1.12.0
Have you
=> make sure all parameters in Model.guess() use prefixes

lmfit/models.py, tests/test_lineshapes_models.py
addresses #566, this time for sure!
basic problem: parameter hints were not using prefix
I did add a test this time!
=> Splitloren hints with prefix

lmfit/minimizer.py, lmfit/model.py, lmfit/models.py, tests/test_model.py
In version 0.9.8 the keyword ```missing``` for the ```Model``` class was deprecated in favor of ```nan_policy``` for consistency with the ```Minimizer``` class. Similarly ```drop``` was deprecated in favor of ```omit``` as an option for ```nan_policy```. In lmfit version 0.9.13 we added an explicit ```FutureWarning``` when these options were still used (see #540), this PR removes them completely as well as the -now no longer needed- compatibility code.
Additionally, the tests are updated to reflect this change and I added a tests to check that the correct option is given to ```nan_policy```.
lmfit: 0.9.13+47.g7d99a32, scipy: 1.3.0, numpy: 1.16.4, asteval: 0.9.14, uncertainties: 3.1.1, six: 1.12.0
Have you
=> Remove deprecated "missing" and "drop"

lmfit/jsonutils.py, tests/test_jsonutils.py
Increase test-coverage for lmfit/jsonutils.py to include test in tests_jsonutils.py. While adding the tests I fixed/changed the following:
* DOC: update docstrings in jsonutils.py 
* FIX: handling of pandas.Series in encode4js()
Currently, there is twice a check for ```isinstance(obj, DataFrame)``` , one of them should be ```isinstance(obj, Series)```. Additionally, a few small changes on how to encode/decode the DataFrame/Series. 
I cannot really think of a situation or test-case for "numpy.ndarray, where dtype is'object", so I didn't add a test for this.
Python: 3.7.4 (default, Jul 11 2019, 08:51:12)
lmfit: 0.9.13+57.gb991b9d, scipy: 1.3.0, numpy: 1.16.4, asteval: 0.9.14, uncertainties: 3.1.1, six: 1.12.0
Have you
=> Add tests for lmfit/jsonutils.py

doc/Makefile, doc/conf.py, doc/installation.rst, doc/sphinx/ext_imgmath.py, requirements-dev.txt
With the previous PR (#573) I accidentally broke generating the documentation in PDF format. We now use automatically generated SVG images (using "jupyter_sphinx") in the HTML documentation - with another file format I couldn't get figures with sufficient resolution. 
However, LaTeX cannot incorporate SVG files and they need to be converted first; fortunately ```sphinx``` has a built-in extension that will take of this (you will need ImageMagick though, but that's pretty standard/easy on Linux or macOS these days). 
This PR fixes the issue and additionally adds the required dependencies for building the documentation to ```installation.rst``` (and ```requirements-dev.txt```).
Have you
=> Fix documentation in PDF format

lmfit/model.py, tests/test_model.py
This addresses (partially) #570:
`inspect.signature` is used to parse argument lists of model functions.  Currently, this is Py3.5+ only, with Python2 sticking to `inspect.getfullargspec`.
Basically, we're not planning on supporting Py2 much longer.  If people have not moved to Py3, I doubt this feature being Py3 only will convince them, but at least we don't need to rely on a 3rd party backport.
This uses `inspect.signature`, the recommended approach to inspecting functions.  It will allow some decorated functions to be used as model functions, addressing #570.
(probably should have an example, not just a test!).
Python: 3.7.3 (default, Mar 27 2019, 16:54:48) 
lmfit: 0.9.13+83.ga3c0939, scipy: 1.3.0, numpy: 1.16.4, asteval: 0.9.13, uncertainties: …
=> use `inspect.signature` for better support of Py3 and wrapped functions

.pre-commit-config.yaml, lmfit/minimizer.py, lmfit/printfuncs.py, tests/test_brute.py, tests/test_printfuncs.py
This PR fixes the issue(s) described in #578. Instead of relying lmfit its internal calculation of function evaluations, which fails when using multiprocessing, determine the number of evaluations from the search-grid directly.
Additionally, a (probably rare) bug was fixed in the comparison comparison of the parameter value when no errorbars could be estimated and ```numdifftools``` is present. The issue appears when no initial value is set, which is allowed for algorithms like ```brute```. 
Test were added/update to cover these changes and, finally, the ```pre-commit``` hooks were updated to their latest versions.
Python: 3.7.4 (default, Aug 14 2019, 15:53:38)
lmfit: 0.9.13+89.geafeaee, scipy: 1.3.1, numpy: 1.17.0, asteval: 0.9.14, uncertainties: 3.1.2, …
=> Fix nfev for brute with multiprocessing

THANKS.txt, doc/installation.rst, doc/whatsnew.rst
This PR updates the release notes and links to them in the documentation under the installation instructions. Additionally, new contributors were added to ```THANKS.txt```.
@newville I think with this we should be about ready to release a new version, or is there anything that I've missed?
Python: 3.7.4 (default, Aug 14 2019, 15:53:38)
lmfit: 0.9.13, scipy: 1.3.1, numpy: 1.17.0, asteval: 0.9.14, uncertainties: 3.1.2, six: 1.12.0
Have you
=> almost ready to release 0.9.14?

lmfit/models.py
This is a one line fix for `models.ExpressionModel()` to not use the now-deprecated `max_time` keyword argument for `asteval.Interpreter()`.
Tested with Py37.
No doc or example changes...
=> remove deprecated max_time from asteval.Interpreter() creation

.gitignore, MANIFEST.in, doc/Makefile, doc/contents.rst, doc/doc_examples_to_gallery.py, doc/index.rst, doc/sphinx/theme/lmfitdoc/layout.html
These are all changes to the doc and build scripts for the examples gallery.
I added "Gallery" to the upper-right section of the doc, just to make it more visible.
I tweaked the gallery generation script.  In the end, this is mostly adding suppression of warnings.
I also changed the Makefile so that the gallery isn't generated every time `sphinx-build` is run, but only when the gallery is empty (as after `make clean`).
@reneeotten Let me know if any of these seem wrong or you don't like any part of this.
Tested with all the sphinx tools up-to-date from Anaconda Python 3.7
=> Tweaks to generating the examples gallery

lmfit/minimizer.py, lmfit/parameter.py
This is an attempt to improve performance or at least document an attempt to improve an occasional performance question.  
This moves the application of parameter bounds from "get time" (that is, explicitly in `_getval()`) to "set time" (in the property setter for `Parameter.value`).    
This might avoid unneeded code branches and over-applications of bounds.  I don't really have an idea how the bench-marking will turn out -- turns out "not much", perhaps as expected.  
But, I also think that this is code is not any less sensible and might be clearer.
One change that was necessary was to move the "set value when restoring from pickle" to as late as possible -- after bounds and expressions had been restored.   That might be   
I did not change any of the tests, but I did add a check of …
=> Getval2setval

.pre-commit-config.yaml, .travis.yml, requirements-dev.txt, tests/test_ampgo.py, tests/test_model.py
A few small changes to Travis:
- install missing ```codecov``` package so that we'll get coverage reports again (I accidentally removed it in commit d7bc8b4f553d5a9065c80df193bd1e8929415d91)
- install the "master" branch of ```asteval``` for PY38 (resolved the failures)
- restrict ```emcee``` < 3.0.0 (the latest release removed the ```PTSampler```; we'll have to see how to handle this, either don't use that sampler anymore or rely on the fork ```ptemcee```
- fix a few test warnings: catch the expected ```RuntimeWarning``` in test_ampgo.py and don't use the deprecated ```assertRaisesRegexp``` anymore for PY3
- update the ```pyupgrade``` pre-commit hook
Python: 3.7.4 (default, Sep 15 2019, 17:02:10)
lmfit: 0.9.14+17.g55c888f, scipy: 1.3.1, numpy: 1.17.2, …
=> fixes for Travis CI and PY38

doc/fitting.rst, examples/doc_fitting_emcee.py, examples/example_emcee_Model_interface.py, lmfit/minimizer.py
EMCEE has two measures to judge whether the fit performed well. Those are autocorrelation time and acceptance fraction (https://arxiv.org/pdf/1202.3665.pdf). 
I added the possibility to access this information to the emcee interface.
lmfit: 0.9.14+20.g8f0f1db, scipy: 1.3.1, numpy: 1.17.2, asteval: 0.9.15, uncertainties: 3.1.2, six: 1.12.0
Have you
- [x ] included docstrings that follow PEP 257?
No, because there is no open issue.
No, since it is an extension to an existing, working interface.
No, though I could easily do it if needed.
=> More information about emcee fit

examples/example_Model_interface.py, lmfit/model.py, lmfit/parameter.py, tests/test_parameter.py
While working on improving the coverage of the test-suite I came across some minor inconsistencies in the ```Parameter.__repr__``` function. 
Consider the following examples:
```
>>>import lmfit
>>>lmfit.Parameter(name=‘test’, value=10)
<Parameter 'test', 10, bounds=[-inf:inf]>
>>>lmfit.Parameter(name='test', value=10, vary=False)
<Parameter 'test', value=10 (fixed), bounds=[-inf:inf]>
>>>lmfit.Parameter()
<Parameter -inf, bounds=[-inf:inf]>
```
Currently, only when a Parameter is fixed or has a ```stderr``` attribute it will show “value”; otherwise is’t just the number.  Additionally, when no ```name``` is specified the output also looks different. 
I suggest to change the behavior so that “value” is always printed ahead of the parameter value, and that when no “name” is specified we …
=> changes to the Parameter class and increase coverage

doc/builtin_models.rst, doc/confidence.rst, doc/fitting.rst, examples/doc_fitting_emcee.py
These are doc and example fixes only, improving the description for using `minimizer.emcee()` and so partly addressing #601.   That is, the docs now sort of explain that ``minimize.emcee()` is not really doing a fit, but instead "only" exploring parameter space.  It still might be nice to move the `emcee` code to be with `conf_interval`, but that is too big of a change for today.
Since this is doc only, my intention is to merge this (once or when tests pass) and then release as 1.0.
If there are any errors, omissions, or inaccuracies in the docs they can be fixed at any time...
=> doc and emcee_example fixes

.pre-commit-config.yaml, doc/builtin_models.rst, doc/faq.rst, doc/model.rst, doc/whatsnew.rst, examples/example_Model_interface.py, examples/example_brute.py, lmfit/confidence.py, lmfit/lineshapes.py, lmfit/minimizer.py, lmfit/models.py, lmfit/parameter.py, lmfit/ui/basefitter.py, setup.py, tests/test_ampgo.py, tests/test_parameter.py, tests/test_printfuncs.py
This PR adds a `pre-commit` hook for `codespell` and correct typos reported by the tool. Additionally, correct the sorting of a few import statements. 
lmfit: 1.0.0+19.gbbb7f60, scipy: 1.4.1, numpy: 1.18.2, asteval: 0.9.18, uncertainties: 3.1.2
Have you
=> Add codespell pre-commit hook

lmfit/parameter.py, tests/test_parameter.py
This PR removes a feature and function, which were deprecated earlier in version 0.9.15.
lmfit: 1.0.0+19.gbbb7f60, scipy: 1.4.1, numpy: 1.18.2, asteval: 0.9.18, uncertainties: 3.1.2
Have you
=> Remove deprecated stuff

doc/conf.py, doc/doc_examples_to_gallery.py, doc/installation.rst, requirements-dev.txt
This PR fixes recent errors when building the documentation and gallery. The ```Pillow``` dependency was made optional in a recent update of ```sphinx-gallery```, but we (apparently) use it. Solved by declaring the `Pillow` dependency explicitly.
lmfit: 1.0.0+24.gc528830, scipy: 1.4.1, numpy: 1.18.2, asteval: 0.9.18, uncertainties: 3.1.2
Have you
=> Fix building the documentation/examples gallery

lmfit/models.py, tests/test_lineshapes_models.py
This ensures similar ``guess_from_peak`` behavior for increasing or decreasing ``x``.
Here are a few small things that I noticed about the function I think can be coded more clearly
1. `` imaxy`` was defined twice and only used once in the line after it is created
1. I think it's better to reply on native NumPy than the ``index_of`` function
1. ``halfmax_vals`` used to define the desired indices of x. It's more straightforward just to get the desired values and to use a more transparent name. 
1. It's better not to conflate the meaning of ``amp`, which is used to refer to both the peak hight and integrated intensity in the function. 
Note 
Fix related to mailing list issue
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/lmfit-py/MUi1GphCxKE
import sys, lmfit, …
=> guess_from_peak and increasing vs. decreasing x

lmfit/models.py
After merging #627 the example ```example_use_pandas.py``` fails. That's because `pandas.Series` cannot be indexed using, for example, '[-1]'. Explicitly convert `x_halfmax` to a NumPy array to make sure it always works correctly.
lmfit: 1.0.0+29.gd211c9b, scipy: 1.4.1, numpy: 1.18.2, asteval: 0.9.18, uncertainties: 3.1.2
Have you
=> FIX: guess_from_peak with pandas.[DataFrame|Series]

lmfit/lineshapes.py, tests/test_builtin_models.py, tests/test_lineshapes.py
This PR contains changes to `lineshapes.py` and its test-suite:
- remove unused `assert_results_close` function
- remove unused `_<func>` functions that shadow the ones in `scipy`
- separate tests for lineshapes and built-in models into two different files
- explicit checking/testing of `form` argument
- minor corrections in docstrings and fix a 'wrong continued indentation'
- use `max(tiny, [decay|expon|sigma])`, where `tiny = np.finfo(np.float64).eps` in `exponential`, `pearson7`, and `logistic` to make sure the functions always give a finite result and there is no `ZeroDivisionError`. I think it's correct like this, but please check.
I've been working on some more explicit for the individual lineshape function, but that's not completely finished yet. I'd prefer to see the response to …
=> lineshapes: clean-up and improve tests coverage

lmfit/parameter.py, tests/test_parameter.py
fixes #636. The value got set first and only afterwards the new bounds got set.
I tried adding a test and then fixed the problem by just moving the code that sets the value to be executed after the new bounds have been set. 
- [x ] Bug fix
Python: 3.7.6 (default, Jan  8 2020, 13:42:34) 
lmfit: 1.0.0+44.g1607727.dirty, scipy: 1.4.1, numpy: 1.18.1, asteval: 0.9.18, uncertainties: 3.0.3
Have you
- [ x] referenced existing Issue and/or provided relevant link to mailing list?
- [ x] squashed/minimized your commits and written descriptive commit messages?
- [ x] added or updated existing tests to cover the changes?
=> Fixed #636: updating a parameter with a new value and bounds uses the new bounds

.pre-commit-config.yaml, examples/doc_model_with_iter_callback.py, examples/example_Model_interface.py, examples/example_brute.py, examples/example_complex_resonator_model.py, lmfit/minimizer.py, lmfit/model.py, lmfit/models.py, setup.cfg, tests/lmfit_testutils.py, tests/test_1variable.py, tests/test_basicfit.py, tests/test_bounded_jacobian.py, tests/test_bounds.py, tests/test_covariance_matrix.py, tests/test_custom_independentvar.py, tests/test_default_kws.py, tests/test_itercb.py, tests/test_manypeaks_speed.py, tests/test_model.py, tests/test_model_uncertainties.py, tests/test_multidatasets.py, tests/test_nose.py, tests/test_pandas.py, tests/test_parameter.py, tests/test_parameters.py, tests/test_stepmodel.py
This PR does the following:
- remove PY2 compatibility code
- adds a test file for `pandas` related tests, with an initial regression test for `guess_from_peak`
- adds a few `pre-commit` hooks
- style fixes and maintenance of many `.py` files
lmfit: 1.0.0+50.g9990d4e, scipy: 1.4.1, numpy: 1.18.2, asteval: 0.9.18, uncertainties: 3.1.2
Have you
=> Remove PY2-compatibility code and fixes prompted by static-code analysis

doc/fitting.rst, doc/model.rst, lmfit/minimizer.py, tests/test_default_kws.py
This adds a `call_kws` attribute to `MinimizerResult` that contains the keyword arguments sent to the underlying solver. 
There are also a few tweaks to tests.
This is basically to inform the user what keywords were actually sent to the solver.
Inspired by https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/lmfit-py/W5nFfIsfSow/DHQHqExqAgAJ
- [*] New feature
Python: 3.7.7 (default, Mar 23 2020, 17:31:31)
lmfit: 1.0.0+79.g382ce5f, scipy: 1.4.1, numpy: 1.18.1, asteval: 0.9.18, uncertainties: 3.1.2
Have you
- [*] verified that existing tests pass locally?
- [*] verified that the documentation builds locally?
- [*] updated the documentation?
=> Add result call kws

.pre-commit-config.yaml, doc/sphinx/ext_imgmath.py, doc/sphinx/ext_mathjax.py, lmfit/_ampgo.py, requirements-dev.txt, tests/NISTModels.py, tests/test_lineshapes.py
A few small maintenance commits to
- update the `pre-commit hooks` and fix a few issues reported by the updated hooks 
- update the extension name from `jupyter_sphinx.execute` to `jupyter_sphinx`, as a consequence we should now also depend on version >=0.24. This was also changed in #642 but in an totally unrelated commit; it's preferable to keep those separated.
lmfit: 1.0.1+3.gdea715a, scipy: 1.4.1, numpy: 1.18.4, asteval: 0.9.18, uncertainties: 3.1.2
Have you
=> fix documentation build + pre-commit hooks

lmfit/model.py
The function `eval_uncertainty` in `model.py` currently does:
```
if params is None:
params = self.params
```
which suggests to me that the intention is to use `params` if provided by the user. However, in the remainder of function it always uses `self.params`, so if a Parameters class is provided by the user it will not be used.
This PR fixes that by replacing `self.params` in the remainder by `params`. If I'm misunderstanding the intention here, please let me know. 
lmfit: 1.0.1+6.g47deb52, scipy: 1.4.1, numpy: 1.18.4, asteval: 0.9.18, uncertainties: 3.1.2
Have you
=> FIX: ModelResult.eval_uncertainty should use provided Parameters

lmfit/lineshapes.py, lmfit/models.py, tests/test_builtin_models.py, tests/test_lineshapes.py
The current option for backwards-compatibility does not warn the user to correct the typo in the lineshape/model name. This commit changes that and emits a `FutureWarning`, which will allows us to remove the incorrectly spelled lineshape/model function in an upcoming release.
See commit f3af0d4c052ca8ae4a4927581ba485c659f18d3c
lmfit: 1.0.1+6.g47deb52, scipy: 1.4.1, numpy: 1.18.4, asteval: 0.9.18, uncertainties: 3.1.2
Have you
=> DEP: add deprecation warnings to donaich lineshape and DonaichModel

.travis.yml
It turns out that we currently do not always test with the most recent packages on Travis CI. For example, inspecting [this build-job](https://travis-ci.org/github/lmfit/lmfit-py/jobs/695727370) shows that `numpy 1.17.2` is being used, whereas the latest upstream version is 1.18.5. This PR corrects that situation.
lmfit: 1.0.1+31.gc30d5ff, scipy: 1.4.1, numpy: 1.18.5, asteval: 0.9.18, uncertainties: 3.1.4
Have you
=> install latest version of requirements on Travis CI

lmfit/minimizer.py, tests/test_covariance_matrix.py
This addresses #655 by explicitly saving and restoring the best-fit values after the numdifftools calculation of the covariance matrix.  A test is added.
Python: 3.7.7 (default, Mar 23 2020, 22:36:06) 
[GCC 7.3.0]
lmfit: 1.0.1+48.g5cb52a0, scipy: 1.4.1, numpy: 1.18.1, asteval: 0.9.18, uncertainties: 3.1.2
Also, numdifftools 0.9.39
Have you
=> Restore vals at calc covar

lmfit/model.py, lmfit/models.py
This PR is based on a post I made to the lmfit Google group (https://groups.google.com/forum/?#!topic/lmfit-py/U3XwKBSLrUQ). Its purpose is to allow third-party packages to determine programmatically all the models defined within lmfit in `models.py` and all the valid forms available to modify some of those models. It makes the following changes:
-  A new variable, `lmfit_models`, which contains a dictionary of all the models, can be directly imported from `models.py`.
- A new Model class attribute, `valid_forms`, contains a tuple of allowed forms. It is empty by default.
- The positional argument, `degree`, of the PolynomialModel constructor is converted to a keyword argument of the same name. This allows the polynomial degree to be set by a `form` keyword argument that would override …
=> Register models

lmfit/minimizer.py, tests/test_nose.py
This makes two separate fairly small changes as bug-fixes to address #665 and #666.
The changes are small, and sort of follow the discussion in the linked issue.  
To solve #665, the values of the 'internal variables' are saved at each call of `__residual()` and then used to set 'best values' if the fit terminates early or unexpectedly. That is slightly different from the solution suggested in #665, but I think it is more obvious and clearer.
To solve #666, the proposed solution was followed and a test added.
Python: 3.7.7 (default, Mar 23 2020, 17:31:31)
lmfit: 1.0.1+61.gfc0cf36.dirty, scipy: 1.4.1, numpy: 1.18.1, asteval: 0.9.18, uncertainties: 3.1.2
Have you
=> save last internal values

tests/NISTModels.py, tests/test_NIST_Strd.py
This fixes the functions for the NIST Strd reference tests so that they first calculate the NIST model function and then subtract the optional `y` values.  There were several functions with sign errors of the type `y - m1 + m2` instead of `y - (m1 + m2)`. 
See:  https://groups.google.com/g/lmfit-py/c/leJvx2M4DkM/m/fWdBapj1AAAJ
```
Python: 3.7.7 (default, Mar 23 2020, 17:31:31)
lmfit: 1.0.1+65.gead6aaa, scipy: 1.4.1, numpy: 1.18.1, asteval: 0.9.18, uncertainties: 3.1.2
```
Have you
=> Fix nist strd

doc/conf.py, doc/doc_examples_to_gallery.py, doc/make.bat, requirements-dev.txt
As promised some time ago, here is the PR to make the docs build cross platform.
I think the main problem with building the docs on Windows were the `RegEx`s for the paths in `sphinx_gallery_conf ` (at least with git bash).
Rewriting `doc/doc_examples_to_gallery.py` to use python to copy files instead of relieing on sys calls to `cp` makes it work on `cmd` and `powershell`.
A positive side effect is that the execution time is only half of what it used to be (5s vs. 10s before).
Windows 10
```
Python: 3.8.5 | packaged by conda-forge | (default, Jul 31 2020, 01:53:45) [MSC v.1916 64 bit (AMD64)]
lmfit: 1.0.1+71.gc67d55e, scipy: 1.5.2, numpy: 1.19.1, asteval: 0.9.18, uncertainties: 3.1.4
```
With:
- `cmd`
- `powershell`
- `git-bash`
Building the docs on Windows with `cmd` or `powershell` can …
=> Make docs build cross platform

tests/test_parameters.py
Fixes #674
The tests fail on Python 3.9. I should have looked at the failure
message more closely, it's just that _ast.Module is ast.Module now.
```
Python: 3.9.0rc1 (default, Sep  3 2020, 19:31:07) 
[GCC 9.3.0]
lmfit: 1.0.1+74.gbc2975e, scipy: 1.5.3, numpy: 1.19.2, asteval: 0.9.19, uncertainties: 3.1.4
```
Have you
=> relax module name check in test_check_ast_errors for python 3.9

lmfit/minimizer.py, tests/test_bounded_jacobian.py
The "scalar" methods (i.e. all except for `leastsq`) do not seem to correctly wrap the provided Jacobian to deal with parameter bounds. In addition, the code seems to attempt to translate the `Dfun` argument to `jac` for these methods, but the code to do so can never succeed (if `jac` is not in `fmin_kws`, popping it will raise an error):
https://github.com/lmfit/lmfit-py/blob/c3d07725a0ca1bcb3241182904f8a3338035edaf/lmfit/minimizer.py#L975-L977
From looking at #80, I think this came about by mixing up the two issues.
This PR should fix the issues, I added a very basic test that basically copies `test_bounded_jac` but uses the `CG` method instead. I guess an additional example or more details in the documentation would be helpful as well, but it'd take me a bit more time to provide this. …
=> Fix use of callable Jacobian for scalar methods

.travis.yml, INSTALL, doc/installation.rst, requirements.txt
This PR bumps the minimum required `numpy` version to 1.18.0. Secondly, to make Travis CI with Python 3.9 and minimum dependency versions build successfully we need to use `scipy==1.3.2`. 
lmfit: 1.0.1+133.g80220c3, scipy: 1.5.4, numpy: 1.19.4, asteval: 0.9.21, uncertainties: 3.1.5
Have you
=> Require numpy>=1.18.0

lmfit/minimizer.py
The [`emcee.EnsembleSampler.run_mcmc`](https://emcee.readthedocs.io/en/stable/user/sampler/#emcee.EnsembleSampler.run_mcmc) function that is used in `Minimizer.emcee` passes keyword
arguments to the [`emcee.EnsembleSampler.sample`](https://emcee.readthedocs.io/en/stable/user/sampler/#emcee.EnsembleSampler.sample) function. Several of these keywords could be useful to change, for example,
`skip_initial_state_check` or `tune`.
In order to facilitate this, I have added an optional parameter to `Minimizer.emcee` called `run_mcmc_kwargs`,
which is a `dict` that will be passed to the `emcee.EnsembleSampler.run_mcmc` function. In this way,
all extra keyword arguments are supported and this code does not need to be updated when extra keyword arguments
are added to `emcee.EnsembleSampler.run_mcmc` …
=> Add the run_mcmc_kwargs argument to Minimizer.emcee

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, lmfit/lineshapes.py, lmfit/minimizer.py, lmfit/models.py, lmfit/parameter.py, tests/test_max_nfev.py, tests/test_model.py, tests/test_models.py, tests/test_saveload.py
This addresses #700 and also a couple of other oddities.  Basically, many of the modules use
`tiny = 2.2e-16` which is "smallest double-precision delta" to mean "very small value" in divide-by-zero tests, etc.   This can lead to frustrating-if-not-exactly-buggy behavior.  
So, this PR increases that "tiny value" to 1.e-15 (coincidentally, `=numpy.finfo(numpy.float64).resolution`).    It also adds an explicit check for "tiny internal value" for bounded parameters and sets that to 0, avoiding "parameter not moving from initial value" as seen in #700. 
A test is added. 
This PR also relaxes the bounds "hint" for the `shift` of SineModel (from [0, 2pi] to [-2pi, 2pi], and extending by a small amount).  Related to that model, it also greatly simplifies the tests of SineModel in …
=> Relax epsilon, some testing updates

.pre-commit-config.yaml, THANKS.txt, doc/_templates/indexsidebar.html, doc/whatsnew.rst, publish_docs.sh
A few small changes to the documentation, making this -hopefully- ready for a new release:
- update `whatsnew.rst` and link the version number in the sidebar to that document
- link to EPUB/PDF/HTML documentation on `gh-pages` instead of `https://cars9.uchicago.edu/software/python/lmfit/`
- update `publish_docs.sh` to build all documentation on `master`, then switch to `gh-pages`. Once on that branch clean-up all the old files first, unpack the latest documentation, and commit with adding the latest `tag` to the commit message. After checking that the commit is indeed correct it can be pushed to `upstream`. 
lmfit: 1.0.1+161.gc8ed043, scipy: 1.6.0, numpy: 1.20.0, asteval: 0.9.21, uncertainties: 3.1.5
Have …
=> DOC: last changes for new release

doc/whatsnew.rst, lmfit/model.py, tests/test_saveload.py
better support for save/load of ExpressionModel, make sure init_params and init_fit get restored for modelresult
This does two things:
1.  make a special case for save/load of ExpressionModels - they're weird enough to need it
2. make sure that init_params and init_fit are correct for a loaded ModelResult.
Basically using the example from https://groups.google.com/g/lmfit-py/c/osukDLEbYT8/m/ATUEu-9rBgAJ
Python: 3.8.5 (default, Sep  4 2020, 02:22:02)
[Clang 10.0.0 ]
lmfit: 1.0.1+173.gbaf4676, scipy: 1.5.2, numpy: 1.19.2, asteval: 0.9.21, uncertainties: 3.1.5
Have you
=> better support for save/load of ExpressionModel

azure-pipelines.yml
Another attempt to get the pipeline for Python3.10-dev to work... Install the latest version of `NumPy` and `SciPy` with `python setup.py install` instead of `pip`. Not sure if it's completely working correctly yet as I get some weirdness when running the actual `lmfit` test-suite... but the building/installing all packages now works. 
No rush to merge this, does not need to be part of the upcoming release. Let's just leave it open until it's all tested and fixed.
=> CI: get testing with Python3.10-devel to work

.pre-commit-config.yaml, azure-pipelines.yml, doc/installation.rst, doc/whatsnew.rst, lmfit/lineshapes.py, lmfit/models.py, requirements.txt, tests/test_builtin_models.py, tests/test_lineshapes.py, tests/test_model.py, tests/test_model_saveload.py
A slightly random selection of changes... sorry about that, but opening a PR for each of them seems silly.
- update `pyupgrade` pre-commit hook
- bump `asteval` requirement to >=0.9.22  to avoid DeprecationWarnings from NumPy that make certain tests in our test-suite fail. Install again fro PyPI on Azure Pipelines instead of upstream's GitHub repository.
- some additional tests for the Model class that I still had around; there is still more to do though, just don't know when
- remove the already earlier deprecated incorrect spelling of the `DonaichModel` and `donaich` lineshape 
lmfit: 1.0.2+5.g955dbe9, scipy: 1.6.0, numpy: 1.20.1, asteval: 0.9.22, uncertainties: 3.1.5
Have you
=> a few minor updates

doc/whatsnew.rst, lmfit/confidence.py, lmfit/model.py, lmfit/parameter.py, tests/test_model.py, tests/test_parameters.py
Since Python 3.6 dictionaries are order-preserving so there is no reason anymore to use `OrderedDict`. This PR removes the use of it, and now the `Parameters` class will inherit from `dict` instead. To keep the output the same we override the `__repr__` method with the one used in `OrderedDict`.
lmfit: 1.0.2+9.gf60d332, scipy: 1.6.0, numpy: 1.20.1, asteval: 0.9.22, uncertainties: 3.1.5
Have you
=> remove use of OrderedDict

tests/test_model.py
Introducing a conditional skip on `TestUserDefiniedModel.test_composite_plotting` in case something's wrong with matplotlib. 
Fixes #712 
The plotting test: `TestUserDefiniedModel.test_composite_plotting` fails when `pip` is used to install `cairosvg` and `matplotlib` on windows. Does not occur when using `conda`. This PR simply causes this test to be skipped in this case.
See: https://github.com/lmfit/lmfit-py/issues/712 and https://github.com/matplotlib/matplotlib/issues/19547
Following the discussion, I decided to simply skip the test, as it is already the intent of the code, using `pytest.importorskip`. However, this weird dependency error causes the call to `import matplotlib.pyplot` to raise `OSError` instead of `ImportError`, so `pytest.importorskip` doesn't catch it. Instead, the …
=> Skipping a plotting test in case `import matplotlib.pyplot` raises OSError

.pre-commit-config.yaml, azure-pipelines.yml, doc/whatsnew.rst, lmfit/model.py, tests/test_confidence.py, tests/test_model.py
As discussed on the mailing-list (see: https://groups.google.com/g/lmfit-py/c/3kxu8OYCAW4/m/61dhxzJkAgAJ) the automatically generate Model names are often not very suitable as figure titles for the Model.plot() functions. It should be possible to pass a `title` to `ax_kws` (or `ax_fit_kws`/`ax_res_kws`) depending on the plot function used; however, after the initialization of the `axes` it is overwritten with `ax.set_title` later.
Added a `title` keyword argument as well that allows for setting the figure title. If used, it will take priority over supplying a `title` to `ax_kws` (or `ax_fit_kws`/`ax_res_kws`).
lmfit: 1.0.2+8.g5016da7, scipy: 1.6.0, numpy: 1.20.1, asteval: 0.9.22, uncertainties: 3.1.5
Have …
=>  FIX: do not override user-specified figure title in Model.plot() functions

lmfit/parameter.py, tests/test_parameters.py
This is a small fix to allow the end users to subclass Parameters. We have found this handy to add 
a few specific convenience methods to our Parameters. Currently a Parameters subclass is lost when a fit is performed
as the parameter is copied into a new instance of the Parameters class. Here we fix that by creating an instance of the 
same class as the original object when doing a deepcopy.
```
lmfit: 1.0.2+21.g8a0cd5c, scipy: 1.6.1, numpy: 1.20.1, asteval: 0.9.23, uncertainties: 3.1.5
```
=> Preserve Parameters subclass in deepcopy

lmfit/model.py
[Issue 528](https://github.com/lmfit/lmfit-py/issues/528) was raised to address why pyplot should be deferred to import only in the functions that need them. However, this behavior regressed in commit d865ddf122b67dfe705a3c1a1e514860a926555d. This pull request restores the correct behavior.
This was discussed in the [mailing list](https://groups.google.com/g/lmfit-py/c/KFrXkubVxsg).
A test might be nice to ensure this doesn't happen again, but I'm not sure how to do that.
Python: 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:12:38) 
[Clang 11.0.1 ]
lmfit: 1.0.2+26.g03daaf8.dirty, scipy: 1.6.2, numpy: 1.20.2, asteval: 0.9.23, uncertainties: 3.1.5
=> Defer import of pyplot

.pre-commit-config.yaml, doc/whatsnew.rst, lmfit/model.py, tests/test_model.py, tests/test_pandas.py
This PR coerces the datatypes for `data` (i.e., y-values) and `independent_var` (i.e., x-values) to `float64` or `complex128` where applicable. I think this covers what was discussed before in a recent issue/PR and does change the dtype now as well for `pandas.Series` and `numpy.ndarray`s. It will still allow for the `independent_var` to be a more complex, user-defined object and all the current tests still pass so I don't think it will have any unintended side-effects but please take a look. 
I know that @newville suggested to add a `"check_independent_vars()` function, but given that some of this already happened in the Model class anyway, I decided against that apporach and just extended the code that was already present.
Python: 3.9.5 (default, May  7 2021, 19:09:51)
[Clang 12.0.0 …
=> Coerce `data` and `independent_vars` in Model class to `float64`/`complex128`

lmfit/model.py, tests/test_model.py
This addresses #710 by adding an explicit step to Model.make_funcargs that says "for each function argument, get the parameter value from the fully-prefixed name".
Python: 3.8.10 | packaged by conda-forge | (default, May 10 2021, 22:58:09)
[Clang 11.1.0 ]
lmfit: 1.0.2.post64+g65f5a4d.d20210705, scipy: 1.7.0, numpy: 1.21.0, asteval: 0.9.25, uncertainties: 3.1.5
Have you
=> Fix model name collisions

lmfit/models.py
fix error message
When creating a lmfit.models.PolynomialModel() with a higher degree than the allowed maximum, the error `TypeError: degree must be an integer less than 7.` is raised. However 7 is an allowed degree and thus it should be `TypeError: degree must be an integer less than 8.`
Python: 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit (AMD64)]
lmfit: 1.0.2, scipy: 1.3.1, numpy: 1.17.3, asteval: 0.9.16, uncertainties: 3.1.2
Have you
=> fix error message of models.PolynomialModel

doc/whatsnew.rst, lmfit/parameter.py, tests/test_jsonutils.py
Addresses #739 by making sure that bounds are set up before setting the parameter value when loading a json or other "stateful" representation of a `Parameter`.
Python: 3.8.10 | packaged by conda-forge | (default, May 10 2021, 22:58:09)
[Clang 11.1.0 ]
lmfit: 1.0.2.post78+g15a952b, scipy: 1.7.0, numpy: 1.21.0, asteval: 0.9.25, uncertainties: 3.1.5
Have you
=> Handle altered json parameters

.github/ISSUE_TEMPLATE.md, .pre-commit-config.yaml, azure-pipelines.yml, doc/conf.py, doc/doc_examples_to_gallery.py, doc/whatsnew.rst, examples/doc_model_with_iter_callback.py, examples/example_brute.py, examples/example_complex_resonator_model.py, examples/example_fit_multi_datasets.py, examples/lmfit_emcee_model_selection.py, lmfit/_ampgo.py, lmfit/confidence.py, lmfit/jsonutils.py, lmfit/lineshapes.py, lmfit/minimizer.py, lmfit/model.py, lmfit/models.py, lmfit/parameter.py, lmfit/printfuncs.py, tests/NISTModels.py, tests/test_NIST_Strd.py, tests/test_manypeaks_speed.py, tests/test_model.py, tests/test_multidatasets.py
This PR transitions to code base to use `f-strings`:
- update to `pre-commit` hooks:(i) remove `--keep-percent-format` argument for `pyupgrade` and (ii) add `flynt` pre-commit hook to make sure that formatting-strings are used (`pyupgrade` isn't all that actively changing things...)
- use these tools in addition to manually going through the code to update the "old" style to f-strings.
In places where changing this would make the code less readable or more complicated I left the original.
Python: 3.9.6 (default, Jul  3 2021, 08:35:53)
[Clang 11.0.3 (clang-1103.0.32.62)]
lmfit: 1.0.2.post65+gd614cd5, scipy: 1.7.0, numpy: 1.21.0, asteval: 0.9.25, uncertainties: 3.1.5
Have you
=> MAINT: transition to f-strings

.codecov.yml, azure-pipelines.yml
The bash uploader for `codecov` will be deprecated soon-ish after the security incident earlier this year. This PR attempts to implement the new approach, including the verification of the signatures/checksums. I cannot really do this locally or on my fork as `codecov` doesn't work there... this might need a few attempts to get it right.
=> CI: switch to new codecov uploader

azure-pipelines.yml, doc/installation.rst, doc/whatsnew.rst, requirements-dev.txt, tests/test_manypeaks_speed.py
The (flaky) test `test_manypeaks_speed.py` fails intermittently for random reasons causing the build to fail while it's not really the case. Label this test as flaky (and install the required package) so that `pytest` will repeat it up to 5 times; it it still fails then, something is probably wrong indeed ;)
Python: 3.9.6 (default, Jul  3 2021, 08:35:53)
[Clang 11.0.3 (clang-1103.0.32.62)]
lmfit: 1.0.2.post73+g1925ecd, scipy: 1.7.1, numpy: 1.21.2, asteval: 0.9.25, uncertainties: 3.1.6
Have you
=> CI/TST: mark test as flaky to avoid intermittent CI failures

doc/whatsnew.rst, lmfit/model.py, lmfit/models.py, tests/test_builtin_models.py, tests/test_model.py
This PR makes `x` an required argument of the `guess` method that is implemented in the Model class and many (all?) of the built-in models. 
Closes: #747
Python: 3.9.7 (default, Sep  6 2021, 12:38:33)
[Clang 12.0.0 (clang-1200.0.32.29)]
lmfit: 1.0.2.post91+g62c0528, scipy: 1.7.1, numpy: 1.21.2, asteval: 0.9.25, uncertainties: 3.1.6
Have you
=> ENH: make ``x`` required argument in guess method

lmfit/minimizer.py
allow 'max_nfev' to map to 'maxiter' for `differential_evolution`.
See https://groups.google.com/g/lmfit-py/c/ddd2wR2NcMg/m/mtBhFj72AwAJ?utm_medium=email&utm_source=footer
Python: 3.8.10 | packaged by conda-forge | (default, May 10 2021, 22:58:09)
[Clang 11.1.0 ]
lmfit: 1.0.2.post96+gfdaf1d1.d20210921, scipy: 1.7.0, numpy: 1.21.0, asteval: 0.9.25, uncertainties: 3.1.5
>>>
Have you
=> differential_evolution should use max_nfev as maxiter

doc/whatsnew.rst, lmfit/lineshapes.py, lmfit/minimizer.py, tests/test_covariance_matrix.py, tests/test_least_squares.py
There are small typos in:
- doc/whatsnew.rst
- lmfit/lineshapes.py
- lmfit/minimizer.py
- tests/test_covariance_matrix.py
- tests/test_least_squares.py
Fixes:
- Should read `uncertainties` rather than `uncertaintes`.
- Should read `returns` rather than `returnins`.
- Should read `intercept` rather than `interceps`.
- Should read `evaluations` rather than `evalutions`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

doc/intro.rst, doc/whatsnew.rst
Correct use of noise versus experimental uncertainty in the documentation (`intro.rst`) reported on the [mailinglist](https://groups.google.com/g/lmfit-py/c/8PyyP93sUvU/m/GYvi8XbBAwAJ) by Andrés Zelcer.
- experimental uncertainties cannot be negative
- add noise to the data and provide synthetic experimental uncertainties
Python: 3.9.7 (default, Sep  6 2021, 12:38:33)
[Clang 12.0.0 (clang-1200.0.32.29)]
lmfit: 1.0.2.post103+g429e247, scipy: 1.7.1, numpy: 1.21.2, asteval: 0.9.25, uncertainties: 3.1.6
Have you
=> DOC: fix use of noise/uncertainty in intro

lmfit/lineshapes.py, lmfit/models.py
The current definition of the Damped Harmonic Oscillator lineshape fails for negative values of the independent variable, `x`. This PR fixes the issue in the `dho` function in lineshapes.py, and uses an analytic expression for the function value when `x=0`. This should work for all values of `gamma` and `sigma`. The default value of `center` is changed to 1, since a zero value makes the function zero for all `x`. In the DampedHarmonicOscillatorModel, the minimum value of `center` is set to 0.
This bug has been discussed in the [LMFIT Mailing List](https://groups.google.com/g/lmfit-py/c/6v2wxb3OSRc/m/Uwyv9mHhAAAJ).
Python: 3.8.10 | packaged by conda-forge | (default, May 10 2021, 22:58:09) 
[Clang 11.1.0 ]
lmfit: 1.0.2.post110+geb5f9c1, scipy: 1.5.4, numpy: 1.20.3, asteval: 0.9.23, …
=> Fix dho lineshape

doc/whatsnew.rst, lmfit/model.py
@newville this PR is possibly a bit more controversial as in the past you've been lukewarm about "fixing" this. I hope this strikes a good balance between convenience when working with built-in models without loosing any generality...I think clarifying the return type more specifically and stating that it is dependent on the model function never hurts. And while looking at this, it's clear that it isn't too difficult  to have the `ConstantModel` and `ComplexConstantModel` work out-of-the box with the `.plot_*()` functions. 
So here we go - let me know what you think:
- specify that the return type of .eval() depends on the model function and clarify the types for the built-in models
- allow for automatic plotting of the built-in `ConstantModel` and `ComplexConstantModel` by coercing their …
=> ENH: handle plotting of (Complex)ConstantModel and specify return types

doc/whatsnew.rst, lmfit/printfuncs.py, tests/test_printfuncs.py, tests/test_stepmodel.py
This fixes the issue reported in #768 regarding the undefined `spercent` variable.
Python: 3.9.9 (main, Nov 16 2021, 07:21:43)
[Clang 11.0.3 (clang-1103.0.32.62)]
lmfit: 1.0.3.post6+g1b9a88f, scipy: 1.7.3, numpy: 1.21.4, asteval: 0.9.25, uncertainties: 3.1.6
Have you
=> FIX: make sure `spercent` is defined

lmfit/minimizer.py
This PR initializes a few more attributes of the `MinimizerResult` class, as discussed on the [mailinglist](https://groups.google.com/g/lmfit-py/c/8o0gezZqs-M/m/Y5M-74inBQAJ).
Python: 3.9.9 (main, Nov 16 2021, 07:21:43)
[Clang 11.0.3 (clang-1103.0.32.62)]
lmfit: 1.0.3.post10+ga7298d4, scipy: 1.7.3, numpy: 1.21.4, asteval: 0.9.25, uncertainties: 3.1.6
Have you
=> ENH: initialize a few more MinimizerResult attributes

doc/whatsnew.rst, lmfit/model.py, tests/test_model.py
... in Composite Model
The independent_vars in the CompositeModel are now no longer only the independent_vars of the left model. 
Now, the independent_vars of the left model and right model are both passed to the independent_vars of the CompositeModel.
To reach that, I simply changed l.1120 in `model.py` from:
```
if 'independent_vars' not in kws:
kws['independent_vars'] = self.left.independent_vars
```
to :
```      
if 'independent_vars' not in kws:
kws['independent_vars'] = list(dict.fromkeys([*self.left.independent_vars, *self.right.independent_vars]))
```
This fix solves the problem described in [detail here](https://github.com/lmfit/lmfit-py/discussions/787).
Python: 3.8.3 (default, Jul  2 2020, 16:21:59)
[GCC 7.3.0]
lmfit: 1.0.3.post31+gb930dde.d20220613, scipy: 1.5.0, numpy: …
=> enabled use of different independent_vars... 

doc/whatsnew.rst, lmfit/models.py
The height factor definition had an error (missing parenthesis). Now it is fixed.
Have you
=> Fixed height factor for Gaussian2dModel

lmfit/model.py
The check for `self.ci_out is None` blocks recalculation of confidence intervals in the event that they have already been calculated. But the "effort saving" technique is too blunt. If repeated calls to `conf_interval` are made with differing `kwargs` the results from the first calculation are unexpectedly returned every call. See Issue https://github.com/lmfit/lmfit-py/issues/791. The resolution is to continue caching the results into `self.ci_out` but to recalculate the results every time `conf_interval` is called. This shifts some "effort saving" responsibility out of `lmfit` to the user.
Python: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
lmfit: 0.0.post2624+g1d011fc, scipy: 1.9.0, numpy: 1.23.1, asteval: 0.9.27, uncertainties: 3.1.7
Have you
=> remove if clause blocking recalculation of conf_interval

doc/builtin_models.rst, doc/whatsnew.rst, lmfit/lineshapes.py, lmfit/models.py, lmfit/parameter.py, tests/test_builtin_models.py
This adds the Pearson4 fit model (original version from Wikipedia), which is a skewed version of Pearson7.
Python: 3.10.4 | packaged by conda-forge | (main, Mar 30 2022, 08:38:02) [MSC v.1916 64 bit (AMD64)]
lmfit: 0.0.post2625+g0b9947a.d20220808, scipy: 1.9.0, numpy: 1.23.1, asteval: 0.9.27, uncertainties: 3.1.7
Have you
=> Add Pearson4 fit model (original Wikipedia version)

doc/model.rst, lmfit/model.py, lmfit/printfuncs.py
Adds R^2 statistic for Model fits, as discussed in #803.
Have you
=> add R^2 statistic for Model

lmfit/lineshapes.py
This PR fixes some deprecation warnings in the tests for `lmfit.lineshapes`. The warnings are of the type:
```
tests/test_lineshapes.py::test_x_float_value[rectangle]
c:\projects\misc\lmfit-py\lmfit\lineshapes.py:478: DeprecationWarning: Calling nonzero on 0d arrays is deprecated, as it behaves surprisingly. Use `atleast_1d(cond).nonzero()` if the old behavior was intended. If the context of this warning is of the form `arr[nonzero(cond)]`, just use `arr[cond]`.
arg1[where(arg1 < 0)] = 0.0
```
Python: 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
lmfit: 1.0.3, scipy: 1.9.2, numpy: 1.23.4, asteval: 0.9.27, uncertainties: 3.1.7
Have you
=> Fix deprecation warnings in the tests of lmfit.lineshapes

doc/whatsnew.rst, lmfit/minimizer.py
In this PR we make two changes to the calculation of the covariance
* If one of the diagonal elements of the calculated covariance is negative we know the result is not good, and we set the covariance to `None`. The `None` value was already used when no covariance calculation was made, or for other issues with the calculation, so this should have limited impact on users.
* In case of a `LinAlgError`  or `ValueError` in the calculation a `None` is returned for the covariance (as before) and the original parameter values are restored. 
A discussion on the changes is in #812. Because of the first change, the warnings  generated when the square root of the negative diagonal elements of the covariance matrix are taken have been removed. If this behaviour is not acceptable, I suggest adding a …
=> Draft: Improve handling of covariance calculation

lmfit/lineshapes.py, lmfit/models.py, tests/test_lineshapes.py
Fix the linear mode for RectangleModel. Also update the documentation and update the tests. (#815)
Tests:
* Using numpy functions now allows lineshape.rectangle to handle single floats, so the tests needed to be updated
* added tests for step and rectangle to make sure we get A/2 at mu1 (and mu2)
Docs:
* update to reflect code and make brackets in LaTeX equations a bit nicer
Python: 3.10.8 (main, Oct 13 2022, 09:48:40) [Clang 14.0.0 (clang-1400.0.29.102)]
lmfit: 1.0.0.post473+g125c830.d20221024, scipy: 1.9.3, numpy: 1.23.4, asteval: 0.9.27, uncertainties: 3.1.7
Have you
=> fix 'linear' mode for RectangleModel (lmfit#815)

doc/constraints.rst, doc/fitting.rst, doc/model.rst
I noticed some typos on my readthrough of the documentation and decided to fix them.
Two were just minor spelling mistakes, but the erroneous return description of `iter_cb()` and the inconsistent variable name in the `decay2()` example were quite confusing to me when I first read them.
```
Python: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:50:36) [MSC v.1929 64 bit (AMD64)]
lmfit: 0.0.post2650+gcda59fc, scipy: 1.9.3, numpy: 1.23.4, asteval: 0.9.27, uncertainties: 3.1.7
```
Have you
(Only changed `rst` files.)
(Does not apply.)
(Only changed documentation.)
I tried, I really did. Since `CONTRIBUTING.md` does not specify with which target to build, I did `make html`. It gets throgh almost everything (building `whatsnew`, showing `100%`) and then fails because it treats the …
=> Fix documentation typos

lmfit/minimizer.py, tests/test_NIST_Strd.py
This ensures that `result.init_vals` is the "user" / "external" values, and adds a new attribute `result._init_vals_internal` to store the initial "internal" values which are needed as initial values.
This addresses #820 
When running tests, I saw some deprecations and addressed some of those, but it seems there are other deprecation warnings that might need more work.
>>> import sys, lmfit, numpy, scipy, asteval, uncertainties
>>> print('Python: {}\n\nlmfit: {}, scipy: {}, numpy: {}, asteval: {}, uncertainties: {}'\
...       .format(sys.version, lmfit.__version__, scipy.__version__, numpy.__version__, \
...       asteval.__version__, uncertainties.__version__))
Python: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:00:52)
[Clang 13.0.1 ]
lmfit: …
=> Correct init_vals

.pre-commit-config.yaml, lmfit/model.py, tests/test_1variable.py, tests/test_NIST_Strd.py, tests/test_model_saveload.py, tests/test_parameter.py
Good day to you!  
We do a lot of fits, and have plans to store them for later use in a database using the `dumps` method of `ModelResult`.
However, we have discovered that the JSON produced by `dumps` does not contain the `residual` field and so the ModelResult that we load from the JSON using `loads` does not properly represent the original for our purposes.  Behold:
```python
import numpy as np
from lmfit.model import Model, ModelResult
from lmfit.parameter import Parameters, Parameter
def mysine(x, amp, freq, shift):
return amp * np.sin(x*freq + shift)
sinemodel = Model(mysine)
pars = sinemodel.make_params(amp=1, freq=0.25, shift=0)
pars['shift'].max = 1
pars['shift'].min = -1
pars['amp'].min = 0.0
xs = np.linspace(0,1)
ys = 0.5 + np.exp(-5*xs) + np.random.normal(scale=0.1, size=50) …
```
=> Include residual in model result json

azure-pipelines.yml, doc/model.rst, doc/whatsnew.rst, examples/doc_model_uncertainty2.py, lmfit/model.py, tests/test_model_saveload.py, tests/test_model_uncertainties.py
This adds calculation of dely for model components to ModelResult.eval_uncertainties, addressing https://github.com/lmfit/lmfit-py/issues/761
It replaces #826 
Python: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:01:00)
[Clang 13.0.1 ]
lmfit: 1.0.3.post76+g44eb363.d20221120, scipy: 1.9.3, numpy: 1.23.4, asteval: 0.9.28, uncertainties: 3.1.7
Have you
=> add calculation of dely for components of a composite model

azure-pipelines.yml, doc/installation.rst, doc/whatsnew.rst, lmfit/minimizer.py, setup.cfg, tests/test_basinhopping.py, tests/test_dual_annealing.py, tests/test_shgo.py
This PR contains the following changes:
- bump minimum requirements for SciPy and NumPy (releases from 2 years ago) and asteval  (to support Python 3.11)
- update keywords for a few minimizers so that they will work with all ScPy version between "minimum required" and "current" version.
Have you
=> MAINT: support py311, bump dependencies, update keywords SciPy minimizers

.pre-commit-config.yaml
While working on #837, I noticed that the pre-commit failed, because the latest version of poetry is apparently incompatible with isort 5.11, see
- https://stackoverflow.com/questions/75269700/pre-commit-fails-to-install-isort-5-11-4-with-error-runtimeerror-the-poetry-co
- https://github.com/PyCQA/isort/issues/2077
- https://github.com/PyCQA/isort/pull/2078
Python: 3.10.9 (main, Dec 08 2022, 14:49:06) [GCC]
lmfit: 1.1.0.post1+g1a3b1009, scipy: 1.10.0, numpy: 1.24.1, asteval: 0.9.28, uncertainties: 3.1.7
=> Update isort to 5.12 in pre-commit hook

lmfit/parameter.py, tests/test_parameters.py
I was making use of the `user_data` attribute of a `Parameter`, and noticed that it is not deep-copied when using the `copy()` method of `Parameters`. Here is a simple example:
```python
import lmfit
def func(x, a):
return a * x
model = lmfit.Model(func)
params = model.make_params()
params.get("a").user_data = {"foo": 123 }
params2 = params.copy()
params2.get("a").user_data["foo"] = 456
print(params.get("a").user_data) # prints {'foo': 456}
```
This PR fixes this behavior.
Python: 3.10.9 (main, Dec 08 2022, 14:49:06) [GCC]
lmfit: 1.1.0.post1+g1a3b1009, scipy: 1.10.0, numpy: 1.24.1, asteval: 0.9.28, uncertainties: 3.1.7
Have you
=> Fix deepcopy of user data

doc/confidence.rst, examples/doc_confidence_chi2_maps.py, lmfit/confidence.py
This adds `chi2_out` and `nsigma` parameters to `conf_interval2d`, and adds documentation and an example of using it to make contour maps from a matrix of chi-square values.
This works to clarify some of the discussion at #848
Python: 3.9.15 (main, Nov 24 2022, 08:29:02)
[Clang 14.0.6 ]
lmfit: 1.1.0.post9+gd2ba8e9.d20230312, scipy: 1.9.3, numpy: 1.23.5, asteval: 0.9.29, uncertainties: 3.1.7
Have you
=> add chi2_out and nsigma options to conf_interval2d

doc/installation.rst
This seems to have slipped in in d32bc7064ec5bbc9d55937599766818e5d58698c
=> Fix typo in installation instructions

examples/doc_builtinmodels_nistgauss.py, examples/doc_builtinmodels_peakmodels.py, examples/doc_confidence_chi2_maps.py, examples/example_fit_with_bounds.py, lmfit/confidence.py, lmfit/minimizer.py, lmfit/model.py, lmfit/printfuncs.py, tests/test_covariance_matrix.py, tests/test_nose.py, tests/test_printfuncs.py
This builds on #852 and adds a fix and test for #855.   And it adds an option for reporting correlations as a table.  Yeah, a bit of a mess, not super focussed.
I think it meets all of these ;)
Have you
Have not yet added to `whatsnew.rst`.
=> More chi2 reporting tweaks

doc/whatsnew.rst, examples/doc_builtinmodels_peakmodels.py, lmfit/parameter.py, tests/test_parameters.py
This makes `Parameter.vary` into a property, wrapping an underlying `._vary` attribute, so that setting `Parameter.vary=True` will erase an existing constraint expression
This addresses the problem described in #859 
Python: 3.11.0 | packaged by conda-forge | (main, Jan 15 2023, 05:44:48) [Clang 14.0.6 ]
lmfit: 1.2.0rc1.post0+g52012fd.d20230405, scipy: 1.10.1, numpy: 1.24.2, asteval: 0.9.29, uncertainties: 3.1.7
Have you
=> make Parameter.vary a property

lmfit/minimizer.py
This sets 'maxfun' for the l-bfgs-b method so that our check of max function evaluations with `max_nfev` will work as advertised.  This will address #864 and #865 
Python: 3.11.0 | packaged by conda-forge | (main, Jan 15 2023, 05:44:48) [Clang 14.0.6 ]
lmfit: 1.2.0.post1+g07b0451.d20230416, scipy: 1.10.1, numpy: 1.24.2, asteval: 0.9.29, uncertainties: 3.1.7
Have you
=> set  'maxfun' for l-bfgs-b method 

lmfit/model.py, tests/test_ampgo.py, tests/test_model.py
This addresses #871 for `Model.make_params()` by better allowing values that can be coerced to `float` to be allowed as "value".
Python: 3.11.0 | packaged by conda-forge | (main, Jan 15 2023, 05:44:48) [Clang 14.0.6 ]
lmfit: 1.2.0.post5+g53118ec, scipy: 1.10.1, numpy: 1.24.2, asteval: 0.9.29, uncertainties: 3.1.7
Have you
=> Make params datatypes

lmfit/model.py, tests/test_model.py
This should fix #893 
Python: 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:17:34) [Clang 14.0.6 ]
lmfit: 1.2.1.post5+g980a5d1, scipy: 1.10.1, numpy: 1.24.3, asteval: 0.9.30, uncertainties: 3.1.7
Have you
=> Make params prefix

tests/test_model.py
The `test_hints_for_peakmodels` from `test_model.py` is failing on my system. I suspect due to changes in the accuracy of np.sin and np.cos in the upcoming numpy 1.25 release. See https://github.com/numpy/numpy/pull/23399. The test  `test_hints_for_peakmodels` fails at the comparison
```
self.assertTrue(param_values['m1_intercept'] < -0.0)
```
due to numerical rounding errors. 
In this PR we increase the threshold of the comparison. Since the test itself is not about the values (according to the docstring about checking asteval), this seems safe.
Python: 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]
lmfit: 1.0.2.post286+g980a5d1, scipy: 1.10.1, numpy: 1.25.0rc1+97.g4e69d516c, asteval: 0.9.30, uncertainties: 3.1.7
Have you
=> Fix test_hints_for_peakmodels from test_models.py

lmfit/parameter.py
This makes sure that the best-fit (or current) values are restored to their original values in `Parameters.create_uvars`.
As shown in #905, values for constraint expressions may be off slightly (around uncertainty or machine precision) without this fix.
Python: 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:17:34) [Clang 14.0.6 ]
lmfit: 1.2.2.post0+g8b2038a.d20230727, scipy: 1.11.1, numpy: 1.25.1, asteval: 0.9.31, uncertainties: 3.1.7
Have you
=> restore best-fit parameter values for high accuracy values of constrained values

doc/fitting.rst, doc/model.rst, tests/test_params_uvars.py
This updates the test and docs to better explain how to use `MinimizerResult.uvars`.
Have you
=> Minimize uvars test

lmfit/model.py, tests/test_model.py
This fixes #921
Python: 3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:35:23) [Clang 15.0.7 ]
lmfit: 1.2.2.post11+g5a081c5.d20231107, scipy: 1.11.3, numpy: 1.26.0, asteval: 0.9.31, uncertainties: 3.1.7
Have you
=> Rsquared with weights

.pre-commit-config.yaml, azure-pipelines.yml, doc/installation.rst, doc/whatsnew.rst, lmfit/minimizer.py, setup.cfg, tests/test_ampgo.py, tests/test_basinhopping.py, tests/test_dual_annealing.py, tests/test_shgo.py
Python 3.7 is EOL remove support and testing for it (adding Python 3.12 and switching to GitHub Actions will be in another PR). Additionally, increase minimum supported NumPy and SciPy versions, including a bit of clean-up to code for additional keywords in newer SciPy versions for some minimizers. 
I would be happy to push the minimum versions to even more recent ones, but I'll leave that decision to @newville (our "official" policy has been to support version that were released up to ~2 years ago).
Python: 3.11.6 (main, Oct  3 2023, 00:01:08) [Clang 15.0.0 (clang-1500.0.40.1)]
lmfit: 1.2.2.post13+gac0d35f0, scipy: 1.11.3, numpy: 1.26.1, asteval: 0.9.31, uncertainties: 3.1.7
Have you
=> Drop support for Python 3.7, increase minimum versions for SciPy/NumPy

lmfit/model.py, tests/test_model_saveload.py
From ISSUE # #931
Using the `dumps` and `loads` methods on the `ModelResult` class does not properly take into account loading user added functional parameter expressions. The `funcdefs` keyword in `loads` enables users to pass functions to add to the the asteval interpreter, but these are not subsequently passed into `Parameters()` where they are actually added to the asteval symtable. This caused deserialization to not work with `ModelResults` that have parameters with user defined functions as expressions.
- [ x] Bug fix
Python: 3.9.7 (default, Oct 15 2021, 14:20:07) 
[Clang 13.0.0 (clang-1300.0.29.3)]
lmfit: 1.2.2, scipy: 1.11.1, numpy: 1.23.5,asteval: 0.9.31, uncertainties: 3.1.7
Have you
- [x ] included docstrings that follow PEP 257?
- [ x] referenced existing Issue and/or provided …
=> propagate funcdefs to Parameters in model.loads

lmfit/jsonutils.py, lmfit/minimizer.py, lmfit/model.py, tests/test_model.py
This fixes some of the save/load issues lingering after #932, and fixes some test deprecatiosn
Here we add a "version 2" of the JSON encoding of `ModelResult`, now relying on `Parameter.dumps()`. 
Tests are not altered, and should still all pass.
Have you
=> Saveload custom func

.gitignore, .pre-commit-config.yaml, azure-pipelines.yml, doc/Makefile, doc/conf.py, doc/installation.rst, doc/model.rst, lmfit/minimizer.py, lmfit/model.py, pyproject.toml
This PR contains a number of commits with small fixes and housekeeping items:
- update NumPy / SciPy versions in CI
- code changes for NumPy v2 compatibility (backwards compatible) 
- documentation changes for style, fix intersphinx mapping, filter spurious link in Gallery
- fix deprecation in SciPy v11.0
Python: 3.12.1 (main, Dec  9 2023, 08:07:48) [Clang 15.0.0 (clang-1500.0.40.1)]
lmfit: 1.2.2.post32+gf4e1e98e, scipy: 1.12.0, numpy: 1.26.3, asteval: 0.9.31, uncertainties: 3.1.7
Have you
=> Collection of small fixes

lmfit/confidence.py
Defining `self.min_rel_change` in confidence.py as variable Fixes #936
This pull request updates the constructor parameters of the ConfidenceInterval class in `confidence.py`. Specifically, it adds a new parameter called `min_rel_change` with a default value of **1e-5**. This change addresses issue #936.
Have you
=> Update ConfidenceInterval class constructor parameters

doc/model.rst, examples/example_basinhopping.py, examples/example_sympy.py, lmfit/minimizer.py, lmfit/model.py, lmfit/models.py, tests/test_model.py
This is a change to ``Model`` to make the assignment of independent variables from function arguments a bit clearer.   This is a more complete version of what @schtandard was trying to do with #925 and #926 (and apologies for taking so long on this!)
With this change, function arguments with non-numeric default values will now be listed as independent variables, by default.  That is, with a mode function of 
```
def mymodel(x, center=5, check_positive=True):
. ...
mod = Model(mymodel)
print(mod.independent_vars)
```
will now give ``['x', 'check_positive']``.  The default value will be kept and used as a default value. 
There is sort of an interesting case of `lmfit.lineshapes.voigt`, which has
```
def voigt(x, amplitude=1.0, center=0.0, sigma=1.0, gamma=None):
"""Return a 1-dimensional …
```
=> More uniform independent vars

lmfit/jsonutils.py
Copy sys.module before iterating over it. 
Closes #948
Python: 3.10.14 (main, Mar 19 2024, 21:46:16) [Clang 15.0.0 (clang-1500.3.9.4)]
lmfit: 1.3.0, scipy: 1.11.4, numpy: 1.26.3,asteval: 0.9.32, uncertainties: 3.1.6###### Link(s)
Have you
=> Use a copy of sys.module when iterating over

lmfit/model.py, lmfit/models.py, tests/test_model.py
This restores the behavior of setting a non-default keyword value for a Model function argument when creating a Model.  That is, in 1.3.0, 
```
from lmfit import Model
from lmfit.lineshapes import step
mymodel  = Model(step, form='erf')
```
could sometimes fail to set the form to `erf`.  This is true in `StepModel`, for example, as it set the independent variables to ['x'].
The fix here is sort of "belt and suspenders" in that: the form above should normally work in 1.3.0, but now that new default value (held in `Model.opts = {'form': 'erf'}`) is used, and then any independent variables are set, and then any runtime keyword arguments.
See #947 
Not being able to leave well enough alone, I also tweaked `Model.__repr__()` to use `Model._reprsting()` and to use `long=True` by default.   With …
=> Allow model opts

lmfit/model.py, tests/test_model_uncertainties.py
Closes: #951.
The solution implemented here is to transform 0-d arrays into 1-d using np.at_least_1d as recommended here: https://stackoverflow.com/a/4565910. 
Python: 3.10.14 (main, Mar 19 2024, 21:46:16) [Clang 15.0.0 (clang-1500.3.9.4)]
lmfit: 1.3.0.post2+gcf2626b7, scipy: 1.11.4, numpy: 1.26.3,asteval: 0.9.32, uncertainties: 3.1.6
Have you
=> transform 0-d arrays into 1-d to check their length

.pre-commit-config.yaml, azure-pipelines.yml, doc/installation.rst, lmfit/parameter.py, pyproject.toml, tests/test_model.py
This fixes a few problems with NumPy 2.
It fixes #958 by explicitly removing a few odd non-serializable functions if using NumPy2 and a version of asteval that still includes those.  That is, this is really a problem with asteval exporting numpy functions that it shouldn't (and are deprecated and not really needed anyway).  But, until that is fixed in asteval (in progress), and that version of asteval is required, it is probably safest to look for and remove those offending functions,
This adds `packaging` as a dependency in order to compare versions.
This also updates the "latest" variations of the tests to use "numpy>=2.0"
This does not alter the test labeled "development version", but that might be slightly dated.
Python: 3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:11:10) …
=> Numpy2 fixes

lmfit/model.py, tests/test_model.py
This fixes #960 and #954.
Python: 3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:35:23) [Clang 15.0.7 ]
lmfit: 1.3.1.post8+gb72cfb28.d20240713, scipy: 1.13.1, numpy: 1.26.4, asteval: 1.0.1, uncertainties: 3.2.2
Have you
=> ensure that correct initial params are used when re-fitting a ModelResult

lmfit/lineshapes.py, lmfit/models.py, tests/test_stepmodel.py
This allows the `step` lineshape and `StepModel` to have values of `sigma<0` to signify a step down (from 1 to 0).
See discussion at: https://groups.google.com/g/lmfit-py/c/aBBzQG0uDK4
Python: 3.12.5 | packaged by conda-forge | (main, Aug  8 2024, 18:31:54) [Clang 16.0.6 ]
lmfit: 1.3.2.post9+g776e14d7.d20241007, scipy: 1.14.0, numpy: 1.26.4, asteval: 1.0.5, uncertainties: 3.2.2.post7+gce16269
Have you
=> Steps with neg sigma

AUTHORS.txt, examples/example_fit_jacobian_benchmark.py, lmfit/minimizer.py, tests/test_jacobian_pickling.py, tests/test_least_squares.py
I encountered some issues while attempting to provide a function to calculate the Jacobian matrix analytically. The issue has been brought up in the mailing list at least a couple of times ([1](https://groups.google.com/g/lmfit-py/c/xwzop5UV82s/m/B-4CexH6EQAJ), [2](https://groups.google.com/g/lmfit-py/c/dTgC_hn-lsw/m/KD_z-SnmBwAJ)). See [PR 908](https://github.com/lmfit/lmfit-py/pull/908) for an earlier pull request (PR) that was ultimately not merged.
The main changes are:
- The `jac` (or `Dfun`) function provided by the user is now wrapped when calling `Minimizer.least_squares`.
- The signature of `Minimizer.__jacobian` now matches the signature of `Minimizer.__residual`, which fixes a bug where an exception was raised due to `Minimizer.__jacobian` receiving an unexpected …
=> Fix issues related to providing a Jacobian function

.pre-commit-config.yaml, azure-pipelines.yml, doc/installation.rst, examples/example_fit_multi_datasets.py, examples/example_fit_multi_datasets_Model-interface.py, lmfit/minimizer.py, pyproject.toml, tests/test_parameter.py, tests/test_parameters.py
This PR drops testing PY38, "officially" adds support for PY313, and starts testing with PY314. 
- updates minimum requires NumPy and SciPy versions
- fix NumPy v2 DeprecationWarning
- adds the example of fitting multiple Gaussian lineshapes using the Model interface
Python: 3.13.1 (main, Dec  7 2024, 10:29:14) [Clang 16.0.0 (clang-1600.0.26.4)]
lmfit: 1.3.2.post20+g8087a61d, scipy: 1.14.1, numpy: 2.2.1, asteval: 1.0.5, uncertainties: 3.2.2
Have you
=> MAINT: drop PY38, support PY313, other miscellaneous updartes 

lmfit/model.py, tests/test_model.py
This adds support of "bare star" in signatures of Model functions to specify keyword-only arguments
See #975 and #976.  This might need more extensive tests. An example might be helpful....
```
Python: 3.12.5 | packaged by conda-forge | (main, Aug  8 2024, 18:31:54) [Clang 16.0.6 ]
lmfit: 1.3.2.post14+g6f8551ac.d20241215, scipy: 1.14.0, numpy: 1.26.4, asteval: 1.0.5, uncertainties: 3.2.2.post7+gce16269
```
Have you
=> Modelfunc barestar

lmfit/models.py, tests/test_model_saveload.py
This explicitly implements the Spline model function, instead of overwriting `SplineModel.eval()`, so that a simple evaluation will work, which is more consistent and needed when loading a saved Model.
This should solve #990 
Python: 3.12.8 | packaged by conda-forge | (main, Dec  5 2024, 14:25:12) [Clang 18.1.8 ]
lmfit: 1.3.2.post23+gec300195, scipy: 1.15.1, numpy: 1.26.4, asteval: 1.0.6, uncertainties: 3.2.2 
Have you
=> Better splinemodel

lmfit/parameter.py, tests/test_confidence.py
This addresses #999 for the recent changes in how `uncertainties` warns about `ufloat()` values with `std_dev=0`. 
The changes here are:
1.  do not test for the content of warning messages from upstream libraries.  They can change.
2. capture and ignore warnings about `stderr=0` when creating `uncertainties.ufloat()` in `conf_interval()`.
Python: 3.12.8 | packaged by conda-forge | (main, Dec  5 2024, 14:25:12) [Clang 18.1.8 ]
lmfit: 1.3.3.post3+g132fef4e, scipy: 1.15.1, numpy: 1.26.4, asteval: 1.0.6, uncertainties: 3.2.3
Have you
=> Fix changed stddev0 warning

doc/installation.rst, doc/model.rst, lmfit/minimizer.py
This pull request improves the documentation page by removing stray backticks that were previously rendered into the page. It also fixes a plural of a linked class that used incorrect syntax and broke the build on `/model.html`.
Before:
After:
Python: 3.13.5 (main, Jun 12 2025, 00:00:00) [GCC 15.1.1 20250521 (Red Hat 15.1.1-2)]
lmfit: 0.0.post2907+g86d7704, scipy: 1.16.0, numpy: 2.3.1, asteval: 1.0.6, uncertainties: 3.2.3
Have you
=> Remove stray backticks in docs; fix plural of linked class

tests/test_model.py
Fix `matplotlib` import to be `matplotlib.pyplot`, as otherwise running the test fails with:
```
$ pytest tests/test_model.py::TestUserDefiniedModel::test_composite_plotting
========================================================= test session starts =========================================================
platform linux -- Python 3.13.5, pytest-8.4.1, pluggy-1.6.0
rootdir: /tmp/lmfit-py
configfile: pyproject.toml
plugins: forked-1.6.0, cov-6.2.1, flaky-3.8.1
collected 1 item
tests/test_model.py F                                                                                                           [100%]
============================================================== FAILURES ===============================================================
____________________________________________ …
```
=> fix import in test_composite_plotting
